# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import llm_v1_pb2 as llm__v1__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llm_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """LLMService is the gRPC interface for the Python LLM sidecar.
    Go calls this for all LLM and embedding operations.
    Python implements this (sidecar/grpc_server.py).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/llm.v1.LLMService/Generate',
                request_serializer=llm__v1__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llm__v1__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GenerateStream = channel.unary_stream(
                '/llm.v1.LLMService/GenerateStream',
                request_serializer=llm__v1__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llm__v1__pb2.GenerateChunk.FromString,
                _registered_method=True)
        self.StructuredOutput = channel.unary_unary(
                '/llm.v1.LLMService/StructuredOutput',
                request_serializer=llm__v1__pb2.StructuredRequest.SerializeToString,
                response_deserializer=llm__v1__pb2.StructuredResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/llm.v1.LLMService/Embed',
                request_serializer=llm__v1__pb2.EmbedRequest.SerializeToString,
                response_deserializer=llm__v1__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.EmbedBatch = channel.unary_unary(
                '/llm.v1.LLMService/EmbedBatch',
                request_serializer=llm__v1__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=llm__v1__pb2.EmbedBatchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/llm.v1.LLMService/Health',
                request_serializer=llm__v1__pb2.HealthRequest.SerializeToString,
                response_deserializer=llm__v1__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GenerateImages = channel.unary_unary(
                '/llm.v1.LLMService/GenerateImages',
                request_serializer=llm__v1__pb2.GenerateImagesRequest.SerializeToString,
                response_deserializer=llm__v1__pb2.GenerateImagesResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """LLMService is the gRPC interface for the Python LLM sidecar.
    Go calls this for all LLM and embedding operations.
    Python implements this (sidecar/grpc_server.py).
    """

    def Generate(self, request, context):
        """Generate produces a text completion given a prompt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStream(self, request, context):
        """GenerateStream streams a text completion chunk-by-chunk (SSE-compatible).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StructuredOutput(self, request, context):
        """StructuredOutput generates a JSON response conforming to the given schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Embed embeds a single text string.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """EmbedBatch embeds multiple texts in one call (up to 250).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health returns the sidecar's readiness state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateImages(self, request, context):
        """GenerateImages generates images using Imagen.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=llm__v1__pb2.GenerateRequest.FromString,
                    response_serializer=llm__v1__pb2.GenerateResponse.SerializeToString,
            ),
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=llm__v1__pb2.GenerateRequest.FromString,
                    response_serializer=llm__v1__pb2.GenerateChunk.SerializeToString,
            ),
            'StructuredOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.StructuredOutput,
                    request_deserializer=llm__v1__pb2.StructuredRequest.FromString,
                    response_serializer=llm__v1__pb2.StructuredResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=llm__v1__pb2.EmbedRequest.FromString,
                    response_serializer=llm__v1__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=llm__v1__pb2.EmbedBatchRequest.FromString,
                    response_serializer=llm__v1__pb2.EmbedBatchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=llm__v1__pb2.HealthRequest.FromString,
                    response_serializer=llm__v1__pb2.HealthResponse.SerializeToString,
            ),
            'GenerateImages': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImages,
                    request_deserializer=llm__v1__pb2.GenerateImagesRequest.FromString,
                    response_serializer=llm__v1__pb2.GenerateImagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.v1.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.v1.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """LLMService is the gRPC interface for the Python LLM sidecar.
    Go calls this for all LLM and embedding operations.
    Python implements this (sidecar/grpc_server.py).
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LLMService/Generate',
            llm__v1__pb2.GenerateRequest.SerializeToString,
            llm__v1__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm.v1.LLMService/GenerateStream',
            llm__v1__pb2.GenerateRequest.SerializeToString,
            llm__v1__pb2.GenerateChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StructuredOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LLMService/StructuredOutput',
            llm__v1__pb2.StructuredRequest.SerializeToString,
            llm__v1__pb2.StructuredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LLMService/Embed',
            llm__v1__pb2.EmbedRequest.SerializeToString,
            llm__v1__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LLMService/EmbedBatch',
            llm__v1__pb2.EmbedBatchRequest.SerializeToString,
            llm__v1__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LLMService/Health',
            llm__v1__pb2.HealthRequest.SerializeToString,
            llm__v1__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.v1.LLMService/GenerateImages',
            llm__v1__pb2.GenerateImagesRequest.SerializeToString,
            llm__v1__pb2.GenerateImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
