# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import wisdev_pb2 as wisdev__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wisdev_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentGatewayStub(object):
    """──────────────────────────────────────────────────────────────────────
    AgentGateway (Go) — Frontend entry point
    ──────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/wisdev.AgentGateway/CreateSession',
                request_serializer=wisdev__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=wisdev__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/wisdev.AgentGateway/GetSession',
                request_serializer=wisdev__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=wisdev__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.ResumeSession = channel.unary_unary(
                '/wisdev.AgentGateway/ResumeSession',
                request_serializer=wisdev__pb2.ResumeSessionRequest.SerializeToString,
                response_deserializer=wisdev__pb2.ResumeSessionResponse.FromString,
                _registered_method=True)
        self.GetNextQuestion = channel.unary_unary(
                '/wisdev.AgentGateway/GetNextQuestion',
                request_serializer=wisdev__pb2.GetNextQuestionRequest.SerializeToString,
                response_deserializer=wisdev__pb2.GetNextQuestionResponse.FromString,
                _registered_method=True)
        self.SubmitAnswer = channel.unary_unary(
                '/wisdev.AgentGateway/SubmitAnswer',
                request_serializer=wisdev__pb2.SubmitAnswerRequest.SerializeToString,
                response_deserializer=wisdev__pb2.SubmitAnswerResponse.FromString,
                _registered_method=True)
        self.ExecutePlan = channel.unary_stream(
                '/wisdev.AgentGateway/ExecutePlan',
                request_serializer=wisdev__pb2.ExecutePlanRequest.SerializeToString,
                response_deserializer=wisdev__pb2.PlanExecutionUpdate.FromString,
                _registered_method=True)
        self.CancelPlan = channel.unary_unary(
                '/wisdev.AgentGateway/CancelPlan',
                request_serializer=wisdev__pb2.CancelPlanRequest.SerializeToString,
                response_deserializer=wisdev__pb2.CancelPlanResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/wisdev.AgentGateway/ListTools',
                request_serializer=wisdev__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=wisdev__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.InvokeTool = channel.unary_unary(
                '/wisdev.AgentGateway/InvokeTool',
                request_serializer=wisdev__pb2.InvokeToolRequest.SerializeToString,
                response_deserializer=wisdev__pb2.InvokeToolResponse.FromString,
                _registered_method=True)
        self.SaveCheckpoint = channel.unary_unary(
                '/wisdev.AgentGateway/SaveCheckpoint',
                request_serializer=wisdev__pb2.SaveCheckpointRequest.SerializeToString,
                response_deserializer=wisdev__pb2.SaveCheckpointResponse.FromString,
                _registered_method=True)
        self.LoadCheckpoint = channel.unary_unary(
                '/wisdev.AgentGateway/LoadCheckpoint',
                request_serializer=wisdev__pb2.LoadCheckpointRequest.SerializeToString,
                response_deserializer=wisdev__pb2.LoadCheckpointResponse.FromString,
                _registered_method=True)
        self.ToolSearch = channel.unary_unary(
                '/wisdev.AgentGateway/ToolSearch',
                request_serializer=wisdev__pb2.ToolSearchRequest.SerializeToString,
                response_deserializer=wisdev__pb2.ToolSearchResponse.FromString,
                _registered_method=True)
        self.ProgrammaticLoop = channel.unary_unary(
                '/wisdev.AgentGateway/ProgrammaticLoop',
                request_serializer=wisdev__pb2.ProgrammaticLoopRequest.SerializeToString,
                response_deserializer=wisdev__pb2.ProgrammaticLoopResponse.FromString,
                _registered_method=True)
        self.StructuredOutput = channel.unary_unary(
                '/wisdev.AgentGateway/StructuredOutput',
                request_serializer=wisdev__pb2.StructuredOutputRequest.SerializeToString,
                response_deserializer=wisdev__pb2.StructuredOutputResponse.FromString,
                _registered_method=True)


class AgentGatewayServicer(object):
    """──────────────────────────────────────────────────────────────────────
    AgentGateway (Go) — Frontend entry point
    ──────────────────────────────────────────────────────────────────────
    """

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToolSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProgrammaticLoop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StructuredOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=wisdev__pb2.CreateSessionRequest.FromString,
                    response_serializer=wisdev__pb2.CreateSessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=wisdev__pb2.GetSessionRequest.FromString,
                    response_serializer=wisdev__pb2.GetSessionResponse.SerializeToString,
            ),
            'ResumeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSession,
                    request_deserializer=wisdev__pb2.ResumeSessionRequest.FromString,
                    response_serializer=wisdev__pb2.ResumeSessionResponse.SerializeToString,
            ),
            'GetNextQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextQuestion,
                    request_deserializer=wisdev__pb2.GetNextQuestionRequest.FromString,
                    response_serializer=wisdev__pb2.GetNextQuestionResponse.SerializeToString,
            ),
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=wisdev__pb2.SubmitAnswerRequest.FromString,
                    response_serializer=wisdev__pb2.SubmitAnswerResponse.SerializeToString,
            ),
            'ExecutePlan': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecutePlan,
                    request_deserializer=wisdev__pb2.ExecutePlanRequest.FromString,
                    response_serializer=wisdev__pb2.PlanExecutionUpdate.SerializeToString,
            ),
            'CancelPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPlan,
                    request_deserializer=wisdev__pb2.CancelPlanRequest.FromString,
                    response_serializer=wisdev__pb2.CancelPlanResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=wisdev__pb2.ListToolsRequest.FromString,
                    response_serializer=wisdev__pb2.ListToolsResponse.SerializeToString,
            ),
            'InvokeTool': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeTool,
                    request_deserializer=wisdev__pb2.InvokeToolRequest.FromString,
                    response_serializer=wisdev__pb2.InvokeToolResponse.SerializeToString,
            ),
            'SaveCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=wisdev__pb2.SaveCheckpointRequest.FromString,
                    response_serializer=wisdev__pb2.SaveCheckpointResponse.SerializeToString,
            ),
            'LoadCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadCheckpoint,
                    request_deserializer=wisdev__pb2.LoadCheckpointRequest.FromString,
                    response_serializer=wisdev__pb2.LoadCheckpointResponse.SerializeToString,
            ),
            'ToolSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ToolSearch,
                    request_deserializer=wisdev__pb2.ToolSearchRequest.FromString,
                    response_serializer=wisdev__pb2.ToolSearchResponse.SerializeToString,
            ),
            'ProgrammaticLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.ProgrammaticLoop,
                    request_deserializer=wisdev__pb2.ProgrammaticLoopRequest.FromString,
                    response_serializer=wisdev__pb2.ProgrammaticLoopResponse.SerializeToString,
            ),
            'StructuredOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.StructuredOutput,
                    request_deserializer=wisdev__pb2.StructuredOutputRequest.FromString,
                    response_serializer=wisdev__pb2.StructuredOutputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wisdev.AgentGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wisdev.AgentGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentGateway(object):
    """──────────────────────────────────────────────────────────────────────
    AgentGateway (Go) — Frontend entry point
    ──────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/CreateSession',
            wisdev__pb2.CreateSessionRequest.SerializeToString,
            wisdev__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/GetSession',
            wisdev__pb2.GetSessionRequest.SerializeToString,
            wisdev__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/ResumeSession',
            wisdev__pb2.ResumeSessionRequest.SerializeToString,
            wisdev__pb2.ResumeSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/GetNextQuestion',
            wisdev__pb2.GetNextQuestionRequest.SerializeToString,
            wisdev__pb2.GetNextQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/SubmitAnswer',
            wisdev__pb2.SubmitAnswerRequest.SerializeToString,
            wisdev__pb2.SubmitAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wisdev.AgentGateway/ExecutePlan',
            wisdev__pb2.ExecutePlanRequest.SerializeToString,
            wisdev__pb2.PlanExecutionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/CancelPlan',
            wisdev__pb2.CancelPlanRequest.SerializeToString,
            wisdev__pb2.CancelPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/ListTools',
            wisdev__pb2.ListToolsRequest.SerializeToString,
            wisdev__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/InvokeTool',
            wisdev__pb2.InvokeToolRequest.SerializeToString,
            wisdev__pb2.InvokeToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/SaveCheckpoint',
            wisdev__pb2.SaveCheckpointRequest.SerializeToString,
            wisdev__pb2.SaveCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/LoadCheckpoint',
            wisdev__pb2.LoadCheckpointRequest.SerializeToString,
            wisdev__pb2.LoadCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToolSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/ToolSearch',
            wisdev__pb2.ToolSearchRequest.SerializeToString,
            wisdev__pb2.ToolSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProgrammaticLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/ProgrammaticLoop',
            wisdev__pb2.ProgrammaticLoopRequest.SerializeToString,
            wisdev__pb2.ProgrammaticLoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StructuredOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AgentGateway/StructuredOutput',
            wisdev__pb2.StructuredOutputRequest.SerializeToString,
            wisdev__pb2.StructuredOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AcademicCapabilityServiceStub(object):
    """──────────────────────────────────────────────────────────────────────
    AcademicCapabilityService (Python) — LLM Reasoning
    ──────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlanResearch = channel.unary_unary(
                '/wisdev.AcademicCapabilityService/PlanResearch',
                request_serializer=wisdev__pb2.PlanResearchRequest.SerializeToString,
                response_deserializer=wisdev__pb2.PlanResearchResponse.FromString,
                _registered_method=True)
        self.VerifyPlan = channel.unary_unary(
                '/wisdev.AcademicCapabilityService/VerifyPlan',
                request_serializer=wisdev__pb2.VerifyPlanRequest.SerializeToString,
                response_deserializer=wisdev__pb2.VerifyPlanResponse.FromString,
                _registered_method=True)
        self.ExecuteCapability = channel.unary_unary(
                '/wisdev.AcademicCapabilityService/ExecuteCapability',
                request_serializer=wisdev__pb2.ExecuteCapabilityRequest.SerializeToString,
                response_deserializer=wisdev__pb2.ExecuteCapabilityResponse.FromString,
                _registered_method=True)
        self.StreamCapability = channel.unary_stream(
                '/wisdev.AcademicCapabilityService/StreamCapability',
                request_serializer=wisdev__pb2.ExecuteCapabilityRequest.SerializeToString,
                response_deserializer=wisdev__pb2.CapabilityChunk.FromString,
                _registered_method=True)
        self.GenerateStructuredOutput = channel.unary_unary(
                '/wisdev.AcademicCapabilityService/GenerateStructuredOutput',
                request_serializer=wisdev__pb2.StructuredOutputRequest.SerializeToString,
                response_deserializer=wisdev__pb2.StructuredOutputResponse.FromString,
                _registered_method=True)
        self.SelectModel = channel.unary_unary(
                '/wisdev.AcademicCapabilityService/SelectModel',
                request_serializer=wisdev__pb2.ModelSelectionRequest.SerializeToString,
                response_deserializer=wisdev__pb2.ModelSelectionResponse.FromString,
                _registered_method=True)
        self.VerifyClaims = channel.unary_unary(
                '/wisdev.AcademicCapabilityService/VerifyClaims',
                request_serializer=wisdev__pb2.VerifyClaimsRequest.SerializeToString,
                response_deserializer=wisdev__pb2.VerifyClaimsResponse.FromString,
                _registered_method=True)
        self.RunScript = channel.unary_unary(
                '/wisdev.AcademicCapabilityService/RunScript',
                request_serializer=wisdev__pb2.RunScriptRequest.SerializeToString,
                response_deserializer=wisdev__pb2.RunScriptResponse.FromString,
                _registered_method=True)


class AcademicCapabilityServiceServicer(object):
    """──────────────────────────────────────────────────────────────────────
    AcademicCapabilityService (Python) — LLM Reasoning
    ──────────────────────────────────────────────────────────────────────
    """

    def PlanResearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStructuredOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyClaims(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcademicCapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlanResearch': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanResearch,
                    request_deserializer=wisdev__pb2.PlanResearchRequest.FromString,
                    response_serializer=wisdev__pb2.PlanResearchResponse.SerializeToString,
            ),
            'VerifyPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPlan,
                    request_deserializer=wisdev__pb2.VerifyPlanRequest.FromString,
                    response_serializer=wisdev__pb2.VerifyPlanResponse.SerializeToString,
            ),
            'ExecuteCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCapability,
                    request_deserializer=wisdev__pb2.ExecuteCapabilityRequest.FromString,
                    response_serializer=wisdev__pb2.ExecuteCapabilityResponse.SerializeToString,
            ),
            'StreamCapability': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCapability,
                    request_deserializer=wisdev__pb2.ExecuteCapabilityRequest.FromString,
                    response_serializer=wisdev__pb2.CapabilityChunk.SerializeToString,
            ),
            'GenerateStructuredOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStructuredOutput,
                    request_deserializer=wisdev__pb2.StructuredOutputRequest.FromString,
                    response_serializer=wisdev__pb2.StructuredOutputResponse.SerializeToString,
            ),
            'SelectModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectModel,
                    request_deserializer=wisdev__pb2.ModelSelectionRequest.FromString,
                    response_serializer=wisdev__pb2.ModelSelectionResponse.SerializeToString,
            ),
            'VerifyClaims': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyClaims,
                    request_deserializer=wisdev__pb2.VerifyClaimsRequest.FromString,
                    response_serializer=wisdev__pb2.VerifyClaimsResponse.SerializeToString,
            ),
            'RunScript': grpc.unary_unary_rpc_method_handler(
                    servicer.RunScript,
                    request_deserializer=wisdev__pb2.RunScriptRequest.FromString,
                    response_serializer=wisdev__pb2.RunScriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wisdev.AcademicCapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wisdev.AcademicCapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AcademicCapabilityService(object):
    """──────────────────────────────────────────────────────────────────────
    AcademicCapabilityService (Python) — LLM Reasoning
    ──────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def PlanResearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AcademicCapabilityService/PlanResearch',
            wisdev__pb2.PlanResearchRequest.SerializeToString,
            wisdev__pb2.PlanResearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AcademicCapabilityService/VerifyPlan',
            wisdev__pb2.VerifyPlanRequest.SerializeToString,
            wisdev__pb2.VerifyPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AcademicCapabilityService/ExecuteCapability',
            wisdev__pb2.ExecuteCapabilityRequest.SerializeToString,
            wisdev__pb2.ExecuteCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wisdev.AcademicCapabilityService/StreamCapability',
            wisdev__pb2.ExecuteCapabilityRequest.SerializeToString,
            wisdev__pb2.CapabilityChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStructuredOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AcademicCapabilityService/GenerateStructuredOutput',
            wisdev__pb2.StructuredOutputRequest.SerializeToString,
            wisdev__pb2.StructuredOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AcademicCapabilityService/SelectModel',
            wisdev__pb2.ModelSelectionRequest.SerializeToString,
            wisdev__pb2.ModelSelectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyClaims(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AcademicCapabilityService/VerifyClaims',
            wisdev__pb2.VerifyClaimsRequest.SerializeToString,
            wisdev__pb2.VerifyClaimsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.AcademicCapabilityService/RunScript',
            wisdev__pb2.RunScriptRequest.SerializeToString,
            wisdev__pb2.RunScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SearchGatewayStub(object):
    """──────────────────────────────────────────────────────────────────────
    SearchGateway (Go) — Parallel Search
    ──────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/wisdev.SearchGateway/Search',
                request_serializer=wisdev__pb2.SearchRequest.SerializeToString,
                response_deserializer=wisdev__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.StreamSearch = channel.unary_stream(
                '/wisdev.SearchGateway/StreamSearch',
                request_serializer=wisdev__pb2.SearchRequest.SerializeToString,
                response_deserializer=wisdev__pb2.SearchUpdate.FromString,
                _registered_method=True)
        self.IterativeSearch = channel.unary_unary(
                '/wisdev.SearchGateway/IterativeSearch',
                request_serializer=wisdev__pb2.IterativeSearchRequest.SerializeToString,
                response_deserializer=wisdev__pb2.IterativeSearchResponse.FromString,
                _registered_method=True)
        self.ReRankResults = channel.unary_unary(
                '/wisdev.SearchGateway/ReRankResults',
                request_serializer=wisdev__pb2.ReRankRequest.SerializeToString,
                response_deserializer=wisdev__pb2.ReRankResponse.FromString,
                _registered_method=True)


class SearchGatewayServicer(object):
    """──────────────────────────────────────────────────────────────────────
    SearchGateway (Go) — Parallel Search
    ──────────────────────────────────────────────────────────────────────
    """

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IterativeSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReRankResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=wisdev__pb2.SearchRequest.FromString,
                    response_serializer=wisdev__pb2.SearchResponse.SerializeToString,
            ),
            'StreamSearch': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSearch,
                    request_deserializer=wisdev__pb2.SearchRequest.FromString,
                    response_serializer=wisdev__pb2.SearchUpdate.SerializeToString,
            ),
            'IterativeSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.IterativeSearch,
                    request_deserializer=wisdev__pb2.IterativeSearchRequest.FromString,
                    response_serializer=wisdev__pb2.IterativeSearchResponse.SerializeToString,
            ),
            'ReRankResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ReRankResults,
                    request_deserializer=wisdev__pb2.ReRankRequest.FromString,
                    response_serializer=wisdev__pb2.ReRankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wisdev.SearchGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wisdev.SearchGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchGateway(object):
    """──────────────────────────────────────────────────────────────────────
    SearchGateway (Go) — Parallel Search
    ──────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.SearchGateway/Search',
            wisdev__pb2.SearchRequest.SerializeToString,
            wisdev__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wisdev.SearchGateway/StreamSearch',
            wisdev__pb2.SearchRequest.SerializeToString,
            wisdev__pb2.SearchUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IterativeSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.SearchGateway/IterativeSearch',
            wisdev__pb2.IterativeSearchRequest.SerializeToString,
            wisdev__pb2.IterativeSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReRankResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wisdev.SearchGateway/ReRankResults',
            wisdev__pb2.ReRankRequest.SerializeToString,
            wisdev__pb2.ReRankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
