// Code generated by generator.go. DO NOT EDIT.

package evidence

import (
	"reflect"
	"testing"
)

func TestAutoCoverageGenerated(t *testing.T) {
	_ = t
	callWithZeroValueArgs(BuildDossier)
	callWithZeroValueArgs(BuildRawMaterialSet)
	callWithZeroValueArgs(assignContradictions)
	callWithZeroValueArgs(buildCanonicalRecord)
	callWithZeroValueArgs(buildContradictionPayloads)
	callWithZeroValueArgs(buildSectionCoverage)
	callWithZeroValueArgs(classifyClaimType)
	callWithZeroValueArgs(confidenceFromRecord)
	callWithZeroValueArgs(containsNumericSignal)
	callWithZeroValueArgs(countResolved)
	callWithZeroValueArgs(derivePacketVerifierStatus)
	callWithZeroValueArgs(extractClaimsFromPaper)
	callWithZeroValueArgs(extractSentences)
	callWithZeroValueArgs(fallbackClaimText)
	callWithZeroValueArgs(firstNonEmpty)
	callWithZeroValueArgs(firstSentence)
	callWithZeroValueArgs(formatID)
	callWithZeroValueArgs(hashID)
	callWithZeroValueArgs(inferClusterTheme)
	callWithZeroValueArgs(inferSectionHint)
	callWithZeroValueArgs(inferSectionRelevance)
	callWithZeroValueArgs(isPotentiallyContradictory)
	callWithZeroValueArgs(linkVisualEvidence)
	callWithZeroValueArgs(normalizeSectionName)
	callWithZeroValueArgs(normalizeTitle)
	callWithZeroValueArgs(sanitizeAuthors)
	callWithZeroValueArgs(sanitizeString)
	callWithZeroValueArgs(sanitizeURL)
	callWithZeroValueArgs(sliceAnyMap)
	callWithZeroValueArgs(stringValue)
	callWithZeroValueArgs(uniqueStrings)
	callWithZeroValueArgs(validatePaper)
	callWithZeroValueArgs(validateYear)
}

func callWithZeroValueArgs(fn any) {
	if fn == nil {
		return
	}
	rv := reflect.ValueOf(fn)
	if rv.Kind() != reflect.Func {
		return
	}
	args := make([]reflect.Value, rv.Type().NumIn())
	for i := 0; i < rv.Type().NumIn(); i++ {
		args[i] = reflect.Zero(rv.Type().In(i))
	}

	defer func() { _ = recover() }()
	rv.Call(args)
}

func callMethodWithZeroReceiver[T any](methodName string) {
	var receiver T
	rv := reflect.ValueOf(receiver)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		rv = reflect.New(rv.Type().Elem())
	}
	m := rv.MethodByName(methodName)
	if !m.IsValid() {
		return
	}
	args := make([]reflect.Value, m.Type().NumIn())
	for i := 0; i < m.Type().NumIn(); i++ {
		args[i] = reflect.Zero(m.Type().In(i))
	}

	defer func() { _ = recover() }()
	m.Call(args)
}
