package main

import (
	"flag"
	"fmt"
	"os"
)

func handleConfig(args []string) {
	if len(args) == 0 {
		fmt.Println(styleError.Render("error: config subcommand required"))
		fmt.Println("Usage: wisdev config <show|validate|init> [flags]")
		os.Exit(1)
	}

	switch args[0] {
	case "show":
		handleConfigShow(args[1:])
	case "validate":
		handleConfigValidate(args[1:])
	case "init":
		handleConfigInit(args[1:])
	default:
		fmt.Fprintln(os.Stderr, styleError.Render("unknown config command: %s\n"), args[0])
		os.Exit(1)
	}
}

func handleConfigShow(args []string) {
	showCmd := flag.NewFlagSet("show", flag.ExitOnError)
	showConfig := showCmd.String("config", "wisdev.yaml", "path to config file")

	if err := showCmd.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	cfg, err := loadConfig(*showConfig)
	if err != nil {
		fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("config error: %v\n", err)))
		os.Exit(1)
	}

	fmt.Println(styleTitle.Render("Configuration"))
	fmt.Println()
	printConfig(cfg)
}

func handleConfigValidate(args []string) {
	valCmd := flag.NewFlagSet("validate", flag.ExitOnError)
	valConfig := valCmd.String("config", "wisdev.yaml", "path to config file")

	if err := valCmd.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	cfg, err := loadConfig(*valConfig)
	if err != nil {
		fmt.Println(styleError.Render(fmt.Sprintf("✖ Invalid config: %v", err)))
		os.Exit(1)
	}

	valid := true
	var issues []string

	if cfg.LLM.APIKey == "" {
		issues = append(issues, "LLM API key is not set (use $WISDEV_LLM_API_KEY env var or set api_key in config)")
		valid = false
	}
	if cfg.LLM.Model == "" {
		issues = append(issues, "LLM model is not set")
		valid = false
	}
	if cfg.Agent.MaxSteps <= 0 {
		issues = append(issues, "max_steps must be positive")
		valid = false
	}
	if cfg.Agent.TokenBudget <= 0 {
		issues = append(issues, "token_budget must be positive")
		valid = false
	}

	if valid {
		fmt.Println(styleSuccess.Render("✔ Configuration is valid"))
		fmt.Println()
		printConfig(cfg)
	} else {
		fmt.Println(styleError.Render("✖ Configuration has issues:"))
		fmt.Println()
		for _, issue := range issues {
			fmt.Printf("  • %s\n", issue)
		}
		os.Exit(1)
	}
}

func handleConfigInit(args []string) {
	initCmd := flag.NewFlagSet("init", flag.ExitOnError)
	initPath := initCmd.String("path", "wisdev.yaml", "output path for config file")
	initProvider := initCmd.String("provider", "openai", "LLM provider: openai, anthropic, custom")
	initModel := initCmd.String("model", "gpt-4o", "LLM model name")
	initStorage := initCmd.String("storage", "memory", "storage backend: memory, sqlite")

	if err := initCmd.Parse(args); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	if _, err := os.Stat(*initPath); err == nil {
		fmt.Fprintln(os.Stderr, styleError.Render("config file already exists: %s\n", *initPath))
		os.Exit(1)
	}

	content := fmt.Sprintf(`# WisDev Agent Configuration
# Generated by wisdev config init

agent:
  mode: autonomous
  max_steps: 15
  token_budget: 100000

llm:
  provider: %s
  model: %s
  api_key: ${WISDEV_LLM_API_KEY}
  base_url: ""

storage:
  type: %s
  dsn: "wisdev_state.db"

observability:
  enable_otel: false
  otlp_endpoint: "localhost:4317"

server:
  http_port: 8081
  grpc_port: 50052
  sidecar_host: localhost
  sidecar_port: 8000
`, *initProvider, *initModel, *initStorage)

	if err := os.WriteFile(*initPath, []byte(content), 0644); err != nil {
		fmt.Fprintln(os.Stderr, styleError.Render(fmt.Sprintf("failed to write config: %v\n", err)))
		os.Exit(1)
	}

	fmt.Println(styleSuccess.Render(fmt.Sprintf("✔ Config created at %s", *initPath)))
	fmt.Println()
	fmt.Println(styleDim.Render("Edit the file and set your WISDEV_LLM_API_KEY environment variable."))
}
