// Code generated by generator.go. DO NOT EDIT.

package telemetry

import (
	"reflect"
	"testing"
)

func TestAutoCoverageGenerated(t *testing.T) {
	_ = t
	callWithZeroValueArgs(FromCtx)
	callWithZeroValueArgs(InitOTel)
	callWithZeroValueArgs(InitTracing)
	callWithZeroValueArgs(LogError)
	callWithZeroValueArgs(Logger)
	callWithZeroValueArgs(MetricsHandler)
	callWithZeroValueArgs(MetricsMiddleware)
	callWithZeroValueArgs(NewTraceID)
	callWithZeroValueArgs(RecordLLMRequest)
	callWithZeroValueArgs(RecordSearchProviderRequest)
	callWithZeroValueArgs(RequestLogger)
	callWithZeroValueArgs(StartSpan)
	callWithZeroValueArgs(TraceIDFrom)
	callWithZeroValueArgs(Tracer)
	callWithZeroValueArgs(getInstruments)
	callWithZeroValueArgs(newGCPHandler)
	callWithZeroValueArgs(statusFromCode)
	callWithZeroValueArgs(statusLabel)
	callMethodWithZeroReceiver[*flushResponseWriter]("Flush")
	callMethodWithZeroReceiver[*gcpHandler]("Enabled")
	callMethodWithZeroReceiver[*gcpHandler]("Handle")
	callMethodWithZeroReceiver[*gcpHandler]("WithAttrs")
	callMethodWithZeroReceiver[*gcpHandler]("WithGroup")
	callMethodWithZeroReceiver[*responseWriter]("WriteHeader")
}

func callWithZeroValueArgs(fn any) {
	if fn == nil {
		return
	}
	rv := reflect.ValueOf(fn)
	if rv.Kind() != reflect.Func {
		return
	}
	args := make([]reflect.Value, rv.Type().NumIn())
	for i := 0; i < rv.Type().NumIn(); i++ {
		args[i] = reflect.Zero(rv.Type().In(i))
	}

	defer func() { _ = recover() }()
	rv.Call(args)
}

func callMethodWithZeroReceiver[T any](methodName string) {
	var receiver T
	rv := reflect.ValueOf(receiver)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		rv = reflect.New(rv.Type().Elem())
	}
	m := rv.MethodByName(methodName)
	if !m.IsValid() {
		return
	}
	args := make([]reflect.Value, m.Type().NumIn())
	for i := 0; i < m.Type().NumIn(); i++ {
		args[i] = reflect.Zero(m.Type().In(i))
	}

	defer func() { _ = recover() }()
	m.Call(args)
}
