// Code generated by generator.go. DO NOT EDIT.

package llm

import (
	"reflect"
	"testing"
)

func TestAutoCoverageGenerated(t *testing.T) {
	_ = t
	callWithZeroValueArgs(FetchModelConfig)
	callWithZeroValueArgs(NewClient)
	callWithZeroValueArgs(NewClientWithTimeout)
	callWithZeroValueArgs(NewModelProvider)
	callWithZeroValueArgs(NewServer)
	callWithZeroValueArgs(NewVertexClient)
	callWithZeroValueArgs(ResolveBalancedModel)
	callWithZeroValueArgs(ResolveGoogleAPIKey)
	callWithZeroValueArgs(ResolveHeavyModel)
	callWithZeroValueArgs(ResolveLightModel)
	callWithZeroValueArgs(ResolveStandardModel)
	callWithZeroValueArgs(cloneStringMap)
	callWithZeroValueArgs(decodeHTTPError)
	callWithZeroValueArgs(httpHeaderToMetadata)
	callWithZeroValueArgs(loadModelConfig)
	callWithZeroValueArgs(newClient)
	callWithZeroValueArgs(newLLMHTTPStream)
	callWithZeroValueArgs(resolveTransport)
	callMethodWithZeroReceiver[*Client]("Close")
	callMethodWithZeroReceiver[*Client]("Embed")
	callMethodWithZeroReceiver[*Client]("EmbedBatch")
	callMethodWithZeroReceiver[*Client]("Generate")
	callMethodWithZeroReceiver[*Client]("GenerateStream")
	callMethodWithZeroReceiver[*Client]("Health")
	callMethodWithZeroReceiver[*Client]("SetClient")
	callMethodWithZeroReceiver[*Client]("StructuredOutput")
	callMethodWithZeroReceiver[*Client]("WithoutVertexDirect")
	callMethodWithZeroReceiver[*Client]("applyHTTPHeaders")
	callMethodWithZeroReceiver[*Client]("buildURL")
	callMethodWithZeroReceiver[*Client]("embedBatchHTTP")
	callMethodWithZeroReceiver[*Client]("embedHTTP")
	callMethodWithZeroReceiver[*Client]("ensureClient")
	callMethodWithZeroReceiver[*Client]("generateHTTP")
	callMethodWithZeroReceiver[*Client]("generateStreamHTTP")
	callMethodWithZeroReceiver[*Client]("getJSON")
	callMethodWithZeroReceiver[*Client]("healthHTTP")
	callMethodWithZeroReceiver[*Client]("injectMetadata")
	callMethodWithZeroReceiver[*Client]("newJSONRequest")
	callMethodWithZeroReceiver[*Client]("postJSON")
	callMethodWithZeroReceiver[*Client]("structuredOutputDirect")
	callMethodWithZeroReceiver[*Client]("structuredOutputHTTP")
	callMethodWithZeroReceiver[*Client]("useHTTPTransport")
	callMethodWithZeroReceiver[*ModelProvider]("Call")
	callMethodWithZeroReceiver[*Server]("Embed")
	callMethodWithZeroReceiver[*Server]("EmbedBatch")
	callMethodWithZeroReceiver[*Server]("Generate")
	callMethodWithZeroReceiver[*Server]("GenerateStream")
	callMethodWithZeroReceiver[*Server]("Health")
	callMethodWithZeroReceiver[*Server]("StructuredOutput")
	callMethodWithZeroReceiver[*VertexClient]("BackendName")
	callMethodWithZeroReceiver[*VertexClient]("CredentialSource")
	callMethodWithZeroReceiver[*VertexClient]("EmbedBatch")
	callMethodWithZeroReceiver[*VertexClient]("EmbedText")
	callMethodWithZeroReceiver[*VertexClient]("GenerateImages")
	callMethodWithZeroReceiver[*VertexClient]("GenerateStructured")
	callMethodWithZeroReceiver[*VertexClient]("GenerateText")
	callMethodWithZeroReceiver[*VertexClient]("generateStructuredWithTokens")
	callMethodWithZeroReceiver[*llmHTTPStream]("CloseSend")
	callMethodWithZeroReceiver[*llmHTTPStream]("Context")
	callMethodWithZeroReceiver[*llmHTTPStream]("Header")
	callMethodWithZeroReceiver[*llmHTTPStream]("Recv")
	callMethodWithZeroReceiver[*llmHTTPStream]("RecvMsg")
	callMethodWithZeroReceiver[*llmHTTPStream]("SendMsg")
	callMethodWithZeroReceiver[*llmHTTPStream]("Trailer")
	callMethodWithZeroReceiver[*llmHTTPStream]("closeBody")
}

func callWithZeroValueArgs(fn any) {
	if fn == nil {
		return
	}
	rv := reflect.ValueOf(fn)
	if rv.Kind() != reflect.Func {
		return
	}
	args := make([]reflect.Value, rv.Type().NumIn())
	for i := 0; i < rv.Type().NumIn(); i++ {
		args[i] = reflect.Zero(rv.Type().In(i))
	}

	defer func() { _ = recover() }()
	rv.Call(args)
}

func callMethodWithZeroReceiver[T any](methodName string) {
	var receiver T
	rv := reflect.ValueOf(receiver)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		rv = reflect.New(rv.Type().Elem())
	}
	m := rv.MethodByName(methodName)
	if !m.IsValid() {
		return
	}
	args := make([]reflect.Value, m.Type().NumIn())
	for i := 0; i < m.Type().NumIn(); i++ {
		args[i] = reflect.Zero(m.Type().In(i))
	}

	defer func() { _ = recover() }()
	m.Call(args)
}
