// Code generated by generator.go. DO NOT EDIT.

package resilience

import (
	"reflect"
	"testing"
)

func TestAutoCoverageGenerated(t *testing.T) {
	_ = t
	callWithZeroValueArgs(CloseSecretManagerClient)
	callWithZeroValueArgs(DefaultTokenCost)
	callWithZeroValueArgs(GetSecret)
	callWithZeroValueArgs(GetSecretFromManager)
	callWithZeroValueArgs(InvalidateSecret)
	callWithZeroValueArgs(IsDegraded)
	callWithZeroValueArgs(MockProjectIDForTest)
	callWithZeroValueArgs(NewBudgetAwareAgentLoop)
	callWithZeroValueArgs(NewBudgetEnforcer)
	callWithZeroValueArgs(NewCircuitBreaker)
	callWithZeroValueArgs(NewCircuitBreakerRegistry)
	callWithZeroValueArgs(NewCircuitBreakerWithFallback)
	callWithZeroValueArgs(NewResourceGovernor)
	callWithZeroValueArgs(NewResourceGovernorWithInterval)
	callWithZeroValueArgs(NewTokenBudget)
	callWithZeroValueArgs(ResolveGoogleCloudProjectID)
	callWithZeroValueArgs(ResolveGoogleCloudProjectIDWithSource)
	callWithZeroValueArgs(SetDegraded)
	callWithZeroValueArgs(getSMClient)
	callWithZeroValueArgs(secretCacheKey)
	callMethodWithZeroReceiver[*BudgetAwareAgentLoop]("CanIterate")
	callMethodWithZeroReceiver[*BudgetAwareAgentLoop]("IterationCount")
	callMethodWithZeroReceiver[*BudgetAwareAgentLoop]("LoopStatus")
	callMethodWithZeroReceiver[*BudgetAwareAgentLoop]("ReachedBudgetLimit")
	callMethodWithZeroReceiver[*BudgetAwareAgentLoop]("ReachedIterationLimit")
	callMethodWithZeroReceiver[*BudgetAwareAgentLoop]("RecordIteration")
	callMethodWithZeroReceiver[*BudgetEnforcer]("ExecuteWithBudget")
	callMethodWithZeroReceiver[*CachedResponseFallback]("Fallback")
	callMethodWithZeroReceiver[*CachedResponseFallback]("Name")
	callMethodWithZeroReceiver[*CircuitBreaker]("Call")
	callMethodWithZeroReceiver[*CircuitBreaker]("Metrics")
	callMethodWithZeroReceiver[*CircuitBreaker]("Reset")
	callMethodWithZeroReceiver[*CircuitBreaker]("State")
	callMethodWithZeroReceiver[*CircuitBreaker]("recordFailure")
	callMethodWithZeroReceiver[*CircuitBreaker]("recordSuccess")
	callMethodWithZeroReceiver[*CircuitBreakerRegistry]("All")
	callMethodWithZeroReceiver[*CircuitBreakerRegistry]("Get")
	callMethodWithZeroReceiver[*CircuitBreakerRegistry]("GetOrCreate")
	callMethodWithZeroReceiver[*CircuitBreakerRegistry]("HealthReport")
	callMethodWithZeroReceiver[*CircuitBreakerRegistry]("ResetAll")
	callMethodWithZeroReceiver[*CircuitBreakerWithFallback]("Call")
	callMethodWithZeroReceiver[*DegradedModeFallback]("Fallback")
	callMethodWithZeroReceiver[*DegradedModeFallback]("Name")
	callMethodWithZeroReceiver[*ResourceGovernor]("Admit")
	callMethodWithZeroReceiver[*ResourceGovernor]("GetHealth")
	callMethodWithZeroReceiver[*ResourceGovernor]("SetStatus")
	callMethodWithZeroReceiver[*ResourceGovernor]("Stop")
	callMethodWithZeroReceiver[*ResourceGovernor]("UpdateHealth")
	callMethodWithZeroReceiver[*ResourceGovernor]("monitor")
	callMethodWithZeroReceiver[*TokenBudget]("Allocate")
	callMethodWithZeroReceiver[*TokenBudget]("AllocateOperation")
	callMethodWithZeroReceiver[*TokenBudget]("Deadline")
	callMethodWithZeroReceiver[*TokenBudget]("ElapsedTime")
	callMethodWithZeroReceiver[*TokenBudget]("Exceeded")
	callMethodWithZeroReceiver[*TokenBudget]("RecordUsage")
	callMethodWithZeroReceiver[*TokenBudget]("Remaining")
	callMethodWithZeroReceiver[*TokenBudget]("Report")
	callMethodWithZeroReceiver[*TokenBudget]("Usage")
	callMethodWithZeroReceiver[*TokenBudget]("Utilization")
}

func callWithZeroValueArgs(fn any) {
	if fn == nil {
		return
	}
	rv := reflect.ValueOf(fn)
	if rv.Kind() != reflect.Func {
		return
	}
	args := make([]reflect.Value, rv.Type().NumIn())
	for i := 0; i < rv.Type().NumIn(); i++ {
		args[i] = reflect.Zero(rv.Type().In(i))
	}

	defer func() { _ = recover() }()
	rv.Call(args)
}

func callMethodWithZeroReceiver[T any](methodName string) {
	var receiver T
	rv := reflect.ValueOf(receiver)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		rv = reflect.New(rv.Type().Elem())
	}
	m := rv.MethodByName(methodName)
	if !m.IsValid() {
		return
	}
	args := make([]reflect.Value, m.Type().NumIn())
	for i := 0; i < m.Type().NumIn(); i++ {
		args[i] = reflect.Zero(m.Type().In(i))
	}

	defer func() { _ = recover() }()
	m.Call(args)
}
