// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/llm/v1/llm_v1.proto

package llmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                                // "" = default (imagen-3.0-generate-001)
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                               // 1-4
	AspectRatio   string                 `protobuf:"bytes,4,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspect_ratio,omitempty"` // "1:1", "4:3", "16:9"
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImagesRequest) Reset() {
	*x = GenerateImagesRequest{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImagesRequest) ProtoMessage() {}

func (x *GenerateImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImagesRequest.ProtoReflect.Descriptor instead.
func (*GenerateImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateImagesRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateImagesRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateImagesRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GenerateImagesRequest) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *GenerateImagesRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GenerateImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*GeneratedImage      `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImagesResponse) Reset() {
	*x = GenerateImagesResponse{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImagesResponse) ProtoMessage() {}

func (x *GenerateImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImagesResponse.ProtoReflect.Descriptor instead.
func (*GenerateImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateImagesResponse) GetImages() []*GeneratedImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GenerateImagesResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GeneratedImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageBytes    []byte                 `protobuf:"bytes,1,opt,name=image_bytes,json=imageBytes,proto3" json:"image_bytes,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedImage) Reset() {
	*x = GeneratedImage{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedImage) ProtoMessage() {}

func (x *GeneratedImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedImage.ProtoReflect.Descriptor instead.
func (*GeneratedImage) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratedImage) GetImageBytes() []byte {
	if x != nil {
		return x.ImageBytes
	}
	return nil
}

func (x *GeneratedImage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"` // optional system instruction
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                   // e.g. "gemini-2.5-flash" or "" for default
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`                     // 0.0–2.0, default 0.7
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`         // 0 = model default
	StopSequences []string               `protobuf:"bytes,6,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // trace_id, user_id, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *GenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateRequest) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *GenerateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	InputTokens   int32                  `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	FinishReason  string                 `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // "stop", "max_tokens", "error"
	LatencyMs     int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *GenerateResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *GenerateResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *GenerateResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *GenerateResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GenerateChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"` // incremental text
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateChunk) Reset() {
	*x = GenerateChunk{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateChunk) ProtoMessage() {}

func (x *GenerateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateChunk.ProtoReflect.Descriptor instead.
func (*GenerateChunk) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *GenerateChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *GenerateChunk) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type StructuredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	JsonSchema    string                 `protobuf:"bytes,3,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"` // JSON Schema as string
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Temperature   float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredRequest) Reset() {
	*x = StructuredRequest{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredRequest) ProtoMessage() {}

func (x *StructuredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredRequest.ProtoReflect.Descriptor instead.
func (*StructuredRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{6}
}

func (x *StructuredRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StructuredRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *StructuredRequest) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *StructuredRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StructuredRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *StructuredRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *StructuredRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StructuredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonResult    string                 `protobuf:"bytes,1,opt,name=json_result,json=jsonResult,proto3" json:"json_result,omitempty"` // validated JSON string
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	InputTokens   int32                  `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	SchemaValid   bool                   `protobuf:"varint,5,opt,name=schema_valid,json=schemaValid,proto3" json:"schema_valid,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"` // populated if schema validation failed
	LatencyMs     int64                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredResponse) Reset() {
	*x = StructuredResponse{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredResponse) ProtoMessage() {}

func (x *StructuredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredResponse.ProtoReflect.Descriptor instead.
func (*StructuredResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{7}
}

func (x *StructuredResponse) GetJsonResult() string {
	if x != nil {
		return x.JsonResult
	}
	return ""
}

func (x *StructuredResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *StructuredResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *StructuredResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *StructuredResponse) GetSchemaValid() bool {
	if x != nil {
		return x.SchemaValid
	}
	return false
}

func (x *StructuredResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StructuredResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                       // "" = default (text-embedding-005)
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"` // "RETRIEVAL_DOCUMENT", "RETRIEVAL_QUERY", etc.
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{8}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *EmbedRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	TokenCount    int32                  `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,3,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{9}
}

func (x *EmbedResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *EmbedResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *EmbedResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type EmbedBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchRequest) Reset() {
	*x = EmbedBatchRequest{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchRequest) ProtoMessage() {}

func (x *EmbedBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchRequest.ProtoReflect.Descriptor instead.
func (*EmbedBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{10}
}

func (x *EmbedBatchRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *EmbedBatchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedBatchRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *EmbedBatchRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EmbedBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbedVector         `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchResponse) Reset() {
	*x = EmbedBatchResponse{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchResponse) ProtoMessage() {}

func (x *EmbedBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchResponse.ProtoReflect.Descriptor instead.
func (*EmbedBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{11}
}

func (x *EmbedBatchResponse) GetEmbeddings() []*EmbedVector {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *EmbedBatchResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *EmbedBatchResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type EmbedVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	TokenCount    int32                  `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedVector) Reset() {
	*x = EmbedVector{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedVector) ProtoMessage() {}

func (x *EmbedVector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedVector.ProtoReflect.Descriptor instead.
func (*EmbedVector) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{12}
}

func (x *EmbedVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *EmbedVector) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ModelsAvailable []string               `protobuf:"bytes,3,rep,name=models_available,json=modelsAvailable,proto3" json:"models_available,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_v1_llm_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_v1_llm_v1_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetModelsAvailable() []string {
	if x != nil {
		return x.ModelsAvailable
	}
	return nil
}

func (x *HealthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_llm_v1_llm_v1_proto protoreflect.FileDescriptor

const file_proto_llm_v1_llm_v1_proto_rawDesc = "" +
	"\n" +
	"\x19proto/llm/v1/llm_v1.proto\x12\x06llm.v1\"\x84\x02\n" +
	"\x15GenerateImagesRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12!\n" +
	"\faspect_ratio\x18\x04 \x01(\tR\vaspectRatio\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.llm.v1.GenerateImagesRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x16GenerateImagesResponse\x12.\n" +
	"\x06images\x18\x01 \x03(\v2\x16.llm.v1.GeneratedImageR\x06images\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\"N\n" +
	"\x0eGeneratedImage\x12\x1f\n" +
	"\vimage_bytes\x18\x01 \x01(\fR\n" +
	"imageBytes\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\xcc\x02\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0estop_sequences\x18\x06 \x03(\tR\rstopSequences\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.llm.v1.GenerateRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x05R\foutputTokens\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\"^\n" +
	"\rGenerateChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\xca\x02\n" +
	"\x11StructuredRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x1f\n" +
	"\vjson_schema\x18\x03 \x01(\tR\n" +
	"jsonSchema\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12C\n" +
	"\bmetadata\x18\a \x03(\v2'.llm.v1.StructuredRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x01\n" +
	"\x12StructuredResponse\x12\x1f\n" +
	"\vjson_result\x18\x01 \x01(\tR\n" +
	"jsonResult\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x05R\foutputTokens\x12!\n" +
	"\fschema_valid\x18\x05 \x01(\bR\vschemaValid\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x03R\tlatencyMs\"\xd2\x01\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12>\n" +
	"\bmetadata\x18\x04 \x03(\v2\".llm.v1.EmbedRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\rEmbedResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x1f\n" +
	"\vtoken_count\x18\x02 \x01(\x05R\n" +
	"tokenCount\x12\x1d\n" +
	"\n" +
	"model_used\x18\x03 \x01(\tR\tmodelUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"\xde\x01\n" +
	"\x11EmbedBatchRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.llm.v1.EmbedBatchRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x12EmbedBatchResponse\x123\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x13.llm.v1.EmbedVectorR\n" +
	"embeddings\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"F\n" +
	"\vEmbedVector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x1f\n" +
	"\vtoken_count\x18\x02 \x01(\x05R\n" +
	"tokenCount\"\x0f\n" +
	"\rHealthRequest\"{\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10models_available\x18\x03 \x03(\tR\x0fmodelsAvailable\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xdf\x03\n" +
	"\n" +
	"LLMService\x12=\n" +
	"\bGenerate\x12\x17.llm.v1.GenerateRequest\x1a\x18.llm.v1.GenerateResponse\x12B\n" +
	"\x0eGenerateStream\x12\x17.llm.v1.GenerateRequest\x1a\x15.llm.v1.GenerateChunk0\x01\x12I\n" +
	"\x10StructuredOutput\x12\x19.llm.v1.StructuredRequest\x1a\x1a.llm.v1.StructuredResponse\x124\n" +
	"\x05Embed\x12\x14.llm.v1.EmbedRequest\x1a\x15.llm.v1.EmbedResponse\x12C\n" +
	"\n" +
	"EmbedBatch\x12\x19.llm.v1.EmbedBatchRequest\x1a\x1a.llm.v1.EmbedBatchResponse\x127\n" +
	"\x06Health\x12\x15.llm.v1.HealthRequest\x1a\x16.llm.v1.HealthResponse\x12O\n" +
	"\x0eGenerateImages\x12\x1d.llm.v1.GenerateImagesRequest\x1a\x1e.llm.v1.GenerateImagesResponseBIZGgithub.com/wisdev-agent/wisdev-agent-os/orchestrator/proto/llm/v1;llmv1b\x06proto3"

var (
	file_proto_llm_v1_llm_v1_proto_rawDescOnce sync.Once
	file_proto_llm_v1_llm_v1_proto_rawDescData []byte
)

func file_proto_llm_v1_llm_v1_proto_rawDescGZIP() []byte {
	file_proto_llm_v1_llm_v1_proto_rawDescOnce.Do(func() {
		file_proto_llm_v1_llm_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_llm_v1_llm_v1_proto_rawDesc), len(file_proto_llm_v1_llm_v1_proto_rawDesc)))
	})
	return file_proto_llm_v1_llm_v1_proto_rawDescData
}

var file_proto_llm_v1_llm_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_llm_v1_llm_v1_proto_goTypes = []any{
	(*GenerateImagesRequest)(nil),  // 0: llm.v1.GenerateImagesRequest
	(*GenerateImagesResponse)(nil), // 1: llm.v1.GenerateImagesResponse
	(*GeneratedImage)(nil),         // 2: llm.v1.GeneratedImage
	(*GenerateRequest)(nil),        // 3: llm.v1.GenerateRequest
	(*GenerateResponse)(nil),       // 4: llm.v1.GenerateResponse
	(*GenerateChunk)(nil),          // 5: llm.v1.GenerateChunk
	(*StructuredRequest)(nil),      // 6: llm.v1.StructuredRequest
	(*StructuredResponse)(nil),     // 7: llm.v1.StructuredResponse
	(*EmbedRequest)(nil),           // 8: llm.v1.EmbedRequest
	(*EmbedResponse)(nil),          // 9: llm.v1.EmbedResponse
	(*EmbedBatchRequest)(nil),      // 10: llm.v1.EmbedBatchRequest
	(*EmbedBatchResponse)(nil),     // 11: llm.v1.EmbedBatchResponse
	(*EmbedVector)(nil),            // 12: llm.v1.EmbedVector
	(*HealthRequest)(nil),          // 13: llm.v1.HealthRequest
	(*HealthResponse)(nil),         // 14: llm.v1.HealthResponse
	nil,                            // 15: llm.v1.GenerateImagesRequest.MetadataEntry
	nil,                            // 16: llm.v1.GenerateRequest.MetadataEntry
	nil,                            // 17: llm.v1.StructuredRequest.MetadataEntry
	nil,                            // 18: llm.v1.EmbedRequest.MetadataEntry
	nil,                            // 19: llm.v1.EmbedBatchRequest.MetadataEntry
}
var file_proto_llm_v1_llm_v1_proto_depIdxs = []int32{
	15, // 0: llm.v1.GenerateImagesRequest.metadata:type_name -> llm.v1.GenerateImagesRequest.MetadataEntry
	2,  // 1: llm.v1.GenerateImagesResponse.images:type_name -> llm.v1.GeneratedImage
	16, // 2: llm.v1.GenerateRequest.metadata:type_name -> llm.v1.GenerateRequest.MetadataEntry
	17, // 3: llm.v1.StructuredRequest.metadata:type_name -> llm.v1.StructuredRequest.MetadataEntry
	18, // 4: llm.v1.EmbedRequest.metadata:type_name -> llm.v1.EmbedRequest.MetadataEntry
	19, // 5: llm.v1.EmbedBatchRequest.metadata:type_name -> llm.v1.EmbedBatchRequest.MetadataEntry
	12, // 6: llm.v1.EmbedBatchResponse.embeddings:type_name -> llm.v1.EmbedVector
	3,  // 7: llm.v1.LLMService.Generate:input_type -> llm.v1.GenerateRequest
	3,  // 8: llm.v1.LLMService.GenerateStream:input_type -> llm.v1.GenerateRequest
	6,  // 9: llm.v1.LLMService.StructuredOutput:input_type -> llm.v1.StructuredRequest
	8,  // 10: llm.v1.LLMService.Embed:input_type -> llm.v1.EmbedRequest
	10, // 11: llm.v1.LLMService.EmbedBatch:input_type -> llm.v1.EmbedBatchRequest
	13, // 12: llm.v1.LLMService.Health:input_type -> llm.v1.HealthRequest
	0,  // 13: llm.v1.LLMService.GenerateImages:input_type -> llm.v1.GenerateImagesRequest
	4,  // 14: llm.v1.LLMService.Generate:output_type -> llm.v1.GenerateResponse
	5,  // 15: llm.v1.LLMService.GenerateStream:output_type -> llm.v1.GenerateChunk
	7,  // 16: llm.v1.LLMService.StructuredOutput:output_type -> llm.v1.StructuredResponse
	9,  // 17: llm.v1.LLMService.Embed:output_type -> llm.v1.EmbedResponse
	11, // 18: llm.v1.LLMService.EmbedBatch:output_type -> llm.v1.EmbedBatchResponse
	14, // 19: llm.v1.LLMService.Health:output_type -> llm.v1.HealthResponse
	1,  // 20: llm.v1.LLMService.GenerateImages:output_type -> llm.v1.GenerateImagesResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_llm_v1_llm_v1_proto_init() }
func file_proto_llm_v1_llm_v1_proto_init() {
	if File_proto_llm_v1_llm_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_llm_v1_llm_v1_proto_rawDesc), len(file_proto_llm_v1_llm_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_llm_v1_llm_v1_proto_goTypes,
		DependencyIndexes: file_proto_llm_v1_llm_v1_proto_depIdxs,
		MessageInfos:      file_proto_llm_v1_llm_v1_proto_msgTypes,
	}.Build()
	File_proto_llm_v1_llm_v1_proto = out.File
	file_proto_llm_v1_llm_v1_proto_goTypes = nil
	file_proto_llm_v1_llm_v1_proto_depIdxs = nil
}
