package docgen

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"

	"github.com/bharathvbcr/wisdev-arc/orchestrator/internal/citations"
	internalwisdev "github.com/bharathvbcr/wisdev-arc/orchestrator/internal/wisdev"
)

// RenderFormat names supported output formats.
type RenderFormat string

const (
	FormatMarkdown RenderFormat = "markdown"
	FormatLaTeX    RenderFormat = "latex"
	FormatHTML     RenderFormat = "html"
	FormatJSON     RenderFormat = "json"
	FormatDOCX     RenderFormat = "docx"
)

// ParseRenderFormat normalizes a render/export format string.
func ParseRenderFormat(raw string) (RenderFormat, error) {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "", "markdown", "md":
		return FormatMarkdown, nil
	case "latex", "tex":
		return FormatLaTeX, nil
	case "html":
		return FormatHTML, nil
	case "json":
		return FormatJSON, nil
	case "docx":
		return FormatDOCX, nil
	default:
		return "", fmt.Errorf("unknown format %q (want markdown, latex, html, json, or docx)", raw)
	}
}

// RenderOptions configures document rendering.
type RenderOptions struct {
	Format        RenderFormat
	CitationStyle citations.Style
	IncludeUncited bool
}

// Render produces a string in the requested format from a canonical Document.
func Render(doc Document, opts RenderOptions) (string, error) {
	style := opts.CitationStyle
	if style == "" {
		style = doc.CitationStyle
	}
	if style == "" {
		style = citations.StyleAPA
	}
	switch opts.Format {
	case FormatJSON:
		encoded, err := json.MarshalIndent(doc, "", "  ")
		if err != nil {
			return "", err
		}
		return string(encoded), nil
	case FormatLaTeX:
		return renderDocumentLaTeX(doc, style), nil
	case FormatHTML:
		return renderDocumentHTML(doc, style), nil
	case FormatDOCX:
		html := renderDocumentHTML(doc, style)
		return exportDOCX(html)
	default:
		return renderDocumentMarkdown(doc, style), nil
	}
}

func renderDocumentMarkdown(doc Document, style citations.Style) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", strings.TrimSpace(doc.Title))
	b.WriteString("_Generated by WisDev DocGen")
	if doc.Intent != "" {
		fmt.Fprintf(&b, " (%s)", doc.Intent.DisplayName())
	}
	b.WriteString("._\n\n")

	for _, section := range doc.Sections {
		title := strings.TrimSpace(section.Title)
		if title == "" {
			title = section.ID
		}
		fmt.Fprintf(&b, "## %s\n\n", title)
		content := strings.TrimSpace(section.Content)
		if content == "" {
			content = "_(no grounded content available for this section yet)_"
		}
		fmt.Fprintf(&b, "%s\n\n", content)
	}

	if len(doc.Visuals) > 0 {
		b.WriteString(renderVisualsMarkdown(doc.Visuals))
	}
	if len(doc.Critique) > 0 {
		b.WriteString(renderCritiqueMarkdown(doc.Critique))
	}
	if len(doc.References) > 0 {
		b.WriteString(renderBibliography(doc.References, style, citations.FormatMarkdown))
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func renderDocumentHTML(doc Document, style citations.Style) string {
	var b strings.Builder
	b.WriteString("<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n")
	fmt.Fprintf(&b, "<title>%s</title>\n", citations.EscapeForHTML(doc.Title))
	b.WriteString("<style>body{font-family:Georgia,serif;max-width:800px;margin:0 auto;padding:2rem;line-height:1.5}h1,h2{color:#222}sup{font-size:0.75em}</style>\n</head>\n<body>\n")
	fmt.Fprintf(&b, "<h1>%s</h1>\n<p><em>Generated by WisDev DocGen (%s).</em></p>\n", citations.EscapeForHTML(doc.Title), doc.Intent.DisplayName())
	for _, section := range doc.Sections {
		title := strings.TrimSpace(section.Title)
		if title == "" {
			title = section.ID
		}
		fmt.Fprintf(&b, "<h2>%s</h2>\n<p>%s</p>\n", citations.EscapeForHTML(title), citations.EscapeForHTMLParagraphs(section.Content))
	}
	if len(doc.Visuals) > 0 {
		b.WriteString("<h2>Figures &amp; Visuals</h2>\n")
		b.WriteString(renderVisualsHTML(doc.Visuals))
	}
	if len(doc.Critique) > 0 {
		b.WriteString(renderCritiqueHTML(doc.Critique))
	}
	if len(doc.References) > 0 {
		b.WriteString("<h2>References</h2>\n<ol>\n")
		for _, line := range formatBibliographyLines(doc.References, style, citations.FormatHTML) {
			fmt.Fprintf(&b, "<li>%s</li>\n", line)
		}
		b.WriteString("</ol>\n")
	}
	b.WriteString("</body>\n</html>")
	return b.String()
}

func renderDocumentLaTeX(doc Document, style citations.Style) string {
	var b strings.Builder
	b.WriteString("\\documentclass[11pt]{article}\n")
	b.WriteString("\\usepackage[utf8]{inputenc}\n\\usepackage[T1]{fontenc}\n\\usepackage{lmodern}\n")
	b.WriteString("\\usepackage[margin=1in]{geometry}\n\\usepackage{graphicx}\n\\usepackage{amsmath}\n")
	b.WriteString("\\usepackage{enumitem}\n\\usepackage{hyperref}\n")
	b.WriteString("\\hypersetup{colorlinks=true, urlcolor=blue, linkcolor=black, citecolor=black}\n\n")
	fmt.Fprintf(&b, "\\title{%s}\n\\author{Generated by WisDev DocGen}\n\\date{\\today}\n\n", latexEscape(doc.Title))
	b.WriteString("\\begin{document}\n\\maketitle\n\n")

	for _, section := range doc.Sections {
		title := strings.TrimSpace(section.Title)
		if title == "" {
			title = section.ID
		}
		if strings.EqualFold(section.ID, "abstract") {
			if content := strings.TrimSpace(section.Content); content != "" {
				b.WriteString("\\begin{abstract}\n")
				b.WriteString(latexParagraphs(content))
				b.WriteString("\n\\end{abstract}\n\n")
			}
			continue
		}
		fmt.Fprintf(&b, "\\section{%s}\n", latexEscape(title))
		content := strings.TrimSpace(section.Content)
		if content == "" {
			b.WriteString("\\emph{(no grounded content available for this section yet)}\n\n")
			continue
		}
		b.WriteString(latexParagraphs(content))
		b.WriteString("\n\n")
	}

	if len(doc.Visuals) > 0 {
		b.WriteString("\\section*{Figures \\& Visuals}\n")
		b.WriteString(renderVisualsLaTeX(doc.Visuals))
	}
	if len(doc.Critique) > 0 {
		b.WriteString(renderCritiqueLatex(doc.Critique))
	}
	if len(doc.References) > 0 {
		b.WriteString("\\begin{thebibliography}{99}\n")
		for i, line := range formatBibliographyLines(doc.References, style, citations.FormatLaTeX) {
			fmt.Fprintf(&b, "\\bibitem{ref%d} %s\n", i+1, line)
		}
		b.WriteString("\\end{thebibliography}\n\n")
	}
	b.WriteString("\\end{document}\n")
	return b.String()
}

func formatBibliographyLines(refs []Reference, style citations.Style, format citations.OutputFormat) []string {
	entries := make([]citations.Entry, 0, len(refs))
	for _, ref := range refs {
		entries = append(entries, ref.ToCitationEntry())
	}
	return citations.FormatBibliography(entries, style, format)
}

func renderBibliography(refs []Reference, style citations.Style, format citations.OutputFormat) string {
	lines := formatBibliographyLines(refs, style, format)
	if len(lines) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("## References\n\n")
	for i, line := range lines {
		fmt.Fprintf(&b, "%d. %s\n", i+1, line)
	}
	b.WriteString("\n")
	return b.String()
}

func exportDOCX(html string) (string, error) {
	if _, err := exec.LookPath("pandoc"); err != nil {
		return "", fmt.Errorf("docx export requires pandoc on PATH: %w", err)
	}
	tmp, err := os.CreateTemp("", "wisdev-docgen-*.html")
	if err != nil {
		return "", err
	}
	htmlPath := tmp.Name()
	defer os.Remove(htmlPath)
	if _, err := tmp.WriteString(html); err != nil {
		tmp.Close()
		return "", err
	}
	tmp.Close()

	outPath := strings.TrimSuffix(htmlPath, ".html") + ".docx"
	defer os.Remove(outPath)
	cmd := exec.Command("pandoc", htmlPath, "-f", "html", "-t", "docx", "-o", outPath)
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("pandoc failed: %v: %s", err, strings.TrimSpace(string(out)))
	}
	data, err := os.ReadFile(outPath)
	if err != nil {
		return "", err
	}
	// Return base64 would be wrong for string - docx is binary.
	// For CLI we write bytes separately; here signal that caller should use ExportBytes.
	return string(data), nil
}

// ExportBytes renders a document and returns raw bytes (for binary formats like docx).
func ExportBytes(doc Document, opts RenderOptions) ([]byte, string, error) {
	if opts.Format == FormatDOCX {
		html := renderDocumentHTML(doc, opts.CitationStyle)
		if _, err := exec.LookPath("pandoc"); err != nil {
			return nil, "text/plain", fmt.Errorf("docx export requires pandoc on PATH: %w", err)
		}
		tmp, err := os.CreateTemp("", "wisdev-docgen-*.html")
		if err != nil {
			return nil, "", err
		}
		htmlPath := tmp.Name()
		defer os.Remove(htmlPath)
		if _, err := tmp.WriteString(html); err != nil {
			tmp.Close()
			return nil, "", err
		}
		tmp.Close()
		outPath := strings.TrimSuffix(htmlPath, ".html") + ".docx"
		defer os.Remove(outPath)
		cmd := exec.Command("pandoc", htmlPath, "-f", "html", "-t", "docx", "-o", outPath)
		if out, err := cmd.CombinedOutput(); err != nil {
			return nil, "", fmt.Errorf("pandoc failed: %v: %s", err, strings.TrimSpace(string(out)))
		}
		data, err := os.ReadFile(outPath)
		if err != nil {
			return nil, "", err
		}
		return data, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", nil
	}
	text, err := Render(doc, opts)
	if err != nil {
		return nil, "", err
	}
	mime := "text/plain"
	switch opts.Format {
	case FormatHTML:
		mime = "text/html"
	case FormatLaTeX:
		mime = "application/x-tex"
	case FormatJSON:
		mime = "application/json"
	case FormatMarkdown:
		mime = "text/markdown"
	}
	return []byte(text), mime, nil
}

func renderVisualsMarkdown(visuals []internalwisdev.VisualArtifact) string {
	var b strings.Builder
	b.WriteString("## Figures & Visuals\n\n")
	for i, visual := range visuals {
		fmt.Fprintf(&b, "**Figure %d. %s**\n\n", i+1, firstNonEmpty(visual.Title, visual.Kind))
		if caption := strings.TrimSpace(visual.Caption); caption != "" {
			fmt.Fprintf(&b, "%s\n\n", caption)
		}
		renderVisualSpecMarkdown(&b, visual)
	}
	return b.String()
}

func renderVisualsHTML(visuals []internalwisdev.VisualArtifact) string {
	var b strings.Builder
	for i, visual := range visuals {
		fmt.Fprintf(&b, "<h3>Figure %d. %s</h3>\n", i+1, citations.EscapeForHTML(firstNonEmpty(visual.Title, visual.Kind)))
		if caption := strings.TrimSpace(visual.Caption); caption != "" {
			fmt.Fprintf(&b, "<p>%s</p>\n", citations.EscapeForHTML(caption))
		}
		renderVisualSpecHTML(&b, visual)
	}
	return b.String()
}

func renderVisualsLaTeX(visuals []internalwisdev.VisualArtifact) string {
	var b strings.Builder
	for i, visual := range visuals {
		fmt.Fprintf(&b, "\\paragraph{Figure %d. %s}\n", i+1, latexEscape(firstNonEmpty(visual.Title, visual.Kind)))
		if caption := strings.TrimSpace(visual.Caption); caption != "" {
			b.WriteString(latexEscape(caption) + "\n\n")
		}
		renderVisualSpecLaTeX(&b, visual)
	}
	return b.String()
}

func renderVisualSpecMarkdown(b *strings.Builder, visual internalwisdev.VisualArtifact) {
	switch spec := visual.Spec.(type) {
	case internalwisdev.ManuscriptTableSpec:
		b.WriteString(renderMarkdownTable(spec))
	case string:
		if trimmed := strings.TrimSpace(spec); trimmed != "" {
			lang := ""
			if strings.EqualFold(visual.SpecType, "mermaid") {
				lang = "mermaid"
			}
			fmt.Fprintf(b, "```%s\n%s\n```\n\n", lang, trimmed)
		}
	default:
		if table, ok := tableSpecFromAny(spec); ok {
			b.WriteString(renderMarkdownTable(table))
		} else if strings.EqualFold(visual.SpecType, "vega_lite") {
			if jsonStr, ok := specAsJSONString(spec); ok {
				fmt.Fprintf(b, "```json\n%s\n```\n\n", jsonStr)
			}
		}
	}
}

func renderVisualSpecHTML(b *strings.Builder, visual internalwisdev.VisualArtifact) {
	switch spec := visual.Spec.(type) {
	case internalwisdev.ManuscriptTableSpec:
		b.WriteString(renderHTMLTable(spec))
	case string:
		if trimmed := strings.TrimSpace(spec); trimmed != "" {
			class := ""
			if strings.EqualFold(visual.SpecType, "mermaid") {
				class = " class=\"language-mermaid\""
			}
			fmt.Fprintf(b, "<pre><code%s>%s</code></pre>\n", class, citations.EscapeForHTML(trimmed))
		}
	default:
		if table, ok := tableSpecFromAny(spec); ok {
			b.WriteString(renderHTMLTable(table))
		} else if strings.EqualFold(visual.SpecType, "vega_lite") {
			if jsonStr, ok := specAsJSONString(spec); ok {
				fmt.Fprintf(b, "<pre><code class=\"language-json\">%s</code></pre>\n", citations.EscapeForHTML(jsonStr))
			}
		}
	}
}

func renderVisualSpecLaTeX(b *strings.Builder, visual internalwisdev.VisualArtifact) {
	switch spec := visual.Spec.(type) {
	case internalwisdev.ManuscriptTableSpec:
		b.WriteString(renderLaTeXTable(spec))
	case string:
		if trimmed := strings.TrimSpace(spec); trimmed != "" {
			b.WriteString("\\par\\noindent\\textit{Diagram source (Mermaid):}\n")
			b.WriteString("{\\footnotesize\n\\begin{verbatim}\n")
			b.WriteString(trimmed + "\n")
			b.WriteString("\\end{verbatim}\n}\n\n")
		}
	default:
		if table, ok := tableSpecFromAny(spec); ok {
			b.WriteString(renderLaTeXTable(table))
		} else if strings.EqualFold(visual.SpecType, "vega_lite") {
			if jsonStr, ok := specAsJSONString(spec); ok {
				b.WriteString("\\par\\noindent\\textit{Vega-Lite specification:}\n")
				b.WriteString("{\\footnotesize\n\\begin{verbatim}\n")
				b.WriteString(jsonStr + "\n")
				b.WriteString("\\end{verbatim}\n}\n\n")
			}
		}
	}
}

func tableSpecFromAny(spec any) (internalwisdev.ManuscriptTableSpec, bool) {
	switch typed := spec.(type) {
	case internalwisdev.ManuscriptTableSpec:
		if len(typed.Headers) == 0 || len(typed.Rows) == 0 {
			return internalwisdev.ManuscriptTableSpec{}, false
		}
		return typed, true
	case map[string]any:
		return tableSpecFromMap(typed)
	default:
		return internalwisdev.ManuscriptTableSpec{}, false
	}
}

func tableSpecFromMap(raw map[string]any) (internalwisdev.ManuscriptTableSpec, bool) {
	headers := stringSliceFromAny(raw["headers"])
	rows := stringMatrixFromAny(raw["rows"])
	if len(headers) == 0 || len(rows) == 0 {
		return internalwisdev.ManuscriptTableSpec{}, false
	}
	return internalwisdev.ManuscriptTableSpec{Headers: headers, Rows: rows}, true
}

func stringSliceFromAny(value any) []string {
	switch typed := value.(type) {
	case []string:
		return typed
	case []any:
		out := make([]string, 0, len(typed))
		for _, item := range typed {
			if str, ok := item.(string); ok {
				out = append(out, str)
			}
		}
		return out
	default:
		return nil
	}
}

func stringMatrixFromAny(value any) [][]string {
	switch typed := value.(type) {
	case [][]string:
		return typed
	case []any:
		out := make([][]string, 0, len(typed))
		for _, row := range typed {
			cells := stringSliceFromAny(row)
			if len(cells) > 0 {
				out = append(out, cells)
			}
		}
		return out
	default:
		return nil
	}
}

func specAsJSONString(spec any) (string, bool) {
	switch typed := spec.(type) {
	case string:
		trimmed := strings.TrimSpace(typed)
		if trimmed == "" {
			return "", false
		}
		return trimmed, true
	default:
		encoded, err := json.MarshalIndent(spec, "", "  ")
		if err != nil {
			return "", false
		}
		return string(encoded), true
	}
}

func renderHTMLTable(spec internalwisdev.ManuscriptTableSpec) string {
	if len(spec.Headers) == 0 || len(spec.Rows) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("<table>\n<thead><tr>\n")
	for _, header := range spec.Headers {
		fmt.Fprintf(&b, "<th>%s</th>\n", citations.EscapeForHTML(header))
	}
	b.WriteString("</tr></thead>\n<tbody>\n")
	for _, row := range spec.Rows {
		b.WriteString("<tr>\n")
		for i := range spec.Headers {
			cell := ""
			if i < len(row) {
				cell = strings.TrimSpace(row[i])
			}
			fmt.Fprintf(&b, "<td>%s</td>\n", citations.EscapeForHTML(cell))
		}
		b.WriteString("</tr>\n")
	}
	b.WriteString("</tbody>\n</table>\n")
	return b.String()
}

func renderMarkdownTable(spec internalwisdev.ManuscriptTableSpec) string {
	if len(spec.Headers) == 0 || len(spec.Rows) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("| " + strings.Join(spec.Headers, " | ") + " |\n")
	b.WriteString("|" + strings.Repeat(" --- |", len(spec.Headers)) + "\n")
	for _, row := range spec.Rows {
		cells := make([]string, len(spec.Headers))
		for i := range cells {
			if i < len(row) {
				cells[i] = strings.ReplaceAll(strings.TrimSpace(row[i]), "|", "\\|")
			}
		}
		b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
	}
	b.WriteString("\n")
	return b.String()
}

func renderLaTeXTable(spec internalwisdev.ManuscriptTableSpec) string {
	if len(spec.Headers) == 0 || len(spec.Rows) == 0 {
		return ""
	}
	colspec := "p{0.24\\textwidth}"
	if len(spec.Headers) >= 2 {
		colspec += "p{0.44\\textwidth}"
	}
	if len(spec.Headers) >= 3 {
		colspec += "p{0.20\\textwidth}"
	}
	for i := 3; i < len(spec.Headers); i++ {
		colspec += "p{0.12\\textwidth}"
	}
	var b strings.Builder
	b.WriteString("\\begin{table}[h]\\centering\\footnotesize\n")
	b.WriteString("\\begin{tabular}{" + colspec + "}\n\\hline\n")
	hdr := make([]string, len(spec.Headers))
	for i, h := range spec.Headers {
		hdr[i] = "\\textbf{" + latexEscape(h) + "}"
	}
	b.WriteString(strings.Join(hdr, " & ") + " \\\\\n\\hline\n")
	for _, row := range spec.Rows {
		cells := make([]string, len(spec.Headers))
		for i := range cells {
			if i < len(row) {
				cells[i] = latexEscape(strings.TrimSpace(row[i]))
			}
		}
		b.WriteString(strings.Join(cells, " & ") + " \\\\\n")
	}
	b.WriteString("\\hline\n\\end{tabular}\n\\end{table}\n\n")
	return b.String()
}

func renderCritiqueMarkdown(critique map[string]any) string {
	if len(critique) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("## Peer Review\n\n")
	if score, ok := critiqueFloat(critique["overallScore"]); ok {
		fmt.Fprintf(&b, "**Overall score:** %.2f\n\n", score)
	}
	if mode, ok := critique["verificationMode"].(string); ok && strings.TrimSpace(mode) != "" {
		fmt.Fprintf(&b, "_Verification: %s._\n\n", strings.TrimSpace(mode))
	}
	writeList := func(label, key string) {
		items := critiqueStringSlice(critique[key])
		if len(items) == 0 {
			return
		}
		fmt.Fprintf(&b, "**%s**\n\n", label)
		for _, item := range items {
			fmt.Fprintf(&b, "- %s\n", item)
		}
		b.WriteString("\n")
	}
	writeList("Strengths", "strengths")
	writeList("Weaknesses", "weaknesses")
	writeList("Risks", "risks")
	writeList("Recommendations", "recommendations")
	return b.String()
}

func renderCritiqueHTML(critique map[string]any) string {
	if len(critique) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("<h2>Peer Review</h2>\n")
	if score, ok := critiqueFloat(critique["overallScore"]); ok {
		fmt.Fprintf(&b, "<p><strong>Overall score:</strong> %.2f</p>\n", score)
	}
	return b.String()
}

func renderCritiqueLatex(critique map[string]any) string {
	if len(critique) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\\section*{Peer Review}\n")
	if score, ok := critiqueFloat(critique["overallScore"]); ok {
		fmt.Fprintf(&b, "\\textbf{Overall score:} %.2f\n\n", score)
	}
	if mode, ok := critique["verificationMode"].(string); ok && strings.TrimSpace(mode) != "" {
		fmt.Fprintf(&b, "\\textit{Verification: %s.}\n\n", latexEscape(strings.TrimSpace(mode)))
	}
	writeList := func(label, key string) {
		items := critiqueStringSlice(critique[key])
		if len(items) == 0 {
			return
		}
		fmt.Fprintf(&b, "\\textbf{%s}\n", latexEscape(label))
		b.WriteString("\\begin{itemize}[leftmargin=1.5em]\n")
		for _, item := range items {
			fmt.Fprintf(&b, "  \\item %s\n", latexEscape(item))
		}
		b.WriteString("\\end{itemize}\n\n")
	}
	writeList("Strengths", "strengths")
	writeList("Weaknesses", "weaknesses")
	writeList("Risks", "risks")
	writeList("Recommendations", "recommendations")
	return b.String()
}

var latexParagraphSplit = regexp.MustCompile(`\n\s*\n+`)

func latexParagraphs(content string) string {
	parts := latexParagraphSplit.Split(strings.TrimSpace(content), -1)
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		if part = strings.TrimSpace(part); part != "" {
			out = append(out, latexEscape(part))
		}
	}
	return strings.Join(out, "\n\n")
}

func latexEscape(s string) string {
	s = strings.NewReplacer(
		"&amp;", "&", "&lt;", "<", "&gt;", ">", "&quot;", "\"", "&#39;", "'", "&apos;", "'",
	).Replace(s)
	s = strings.NewReplacer(
		"\u2014", "---", "\u2013", "--",
		"\u2018", "`", "\u2019", "'",
		"\u201c", "``", "\u201d", "''",
		"\u2026", "...", "\u00a0", " ", "\u2009", " ", "\u202f", " ",
		"\u2212", "-",
	).Replace(s)
	var b strings.Builder
	for _, ch := range s {
		switch ch {
		case '\\':
			b.WriteString("\\textbackslash{}")
		case '&':
			b.WriteString("\\&")
		case '%':
			b.WriteString("\\%")
		case '$':
			b.WriteString("\\$")
		case '#':
			b.WriteString("\\#")
		case '_':
			b.WriteString("\\_")
		case '{':
			b.WriteString("\\{")
		case '}':
			b.WriteString("\\}")
		case '~':
			b.WriteString("\\textasciitilde{}")
		case '^':
			b.WriteString("\\textasciicircum{}")
		default:
			b.WriteRune(ch)
		}
	}
	return b.String()
}

func critiqueStringSlice(value any) []string {
	switch typed := value.(type) {
	case []string:
		return typed
	case []any:
		out := make([]string, 0, len(typed))
		for _, item := range typed {
			if str, ok := item.(string); ok && strings.TrimSpace(str) != "" {
				out = append(out, str)
			}
		}
		return out
	default:
		return nil
	}
}

func critiqueFloat(value any) (float64, bool) {
	switch typed := value.(type) {
	case float64:
		return typed, true
	case float32:
		return float64(typed), true
	case int:
		return float64(typed), true
	case int64:
		return float64(typed), true
	default:
		return 0, false
	}
}
