// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/llm/llm.proto

package llm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prompt          string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SystemPrompt    string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Temperature     float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens       int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	StopSequences   []string               `protobuf:"bytes,6,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ThinkingBudget  *int32                 `protobuf:"varint,8,opt,name=thinking_budget,json=thinkingBudget,proto3,oneof" json:"thinking_budget,omitempty"`
	ServiceTier     string                 `protobuf:"bytes,9,opt,name=service_tier,json=serviceTier,proto3" json:"service_tier,omitempty"`
	RetryProfile    string                 `protobuf:"bytes,10,opt,name=retry_profile,json=retryProfile,proto3" json:"retry_profile,omitempty"`
	RequestClass    string                 `protobuf:"bytes,11,opt,name=request_class,json=requestClass,proto3" json:"request_class,omitempty"`
	LatencyBudgetMs int32                  `protobuf:"varint,12,opt,name=latency_budget_ms,json=latencyBudgetMs,proto3" json:"latency_budget_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_proto_llm_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *GenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateRequest) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *GenerateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GenerateRequest) GetThinkingBudget() int32 {
	if x != nil && x.ThinkingBudget != nil {
		return *x.ThinkingBudget
	}
	return 0
}

func (x *GenerateRequest) GetServiceTier() string {
	if x != nil {
		return x.ServiceTier
	}
	return ""
}

func (x *GenerateRequest) GetRetryProfile() string {
	if x != nil {
		return x.RetryProfile
	}
	return ""
}

func (x *GenerateRequest) GetRequestClass() string {
	if x != nil {
		return x.RequestClass
	}
	return ""
}

func (x *GenerateRequest) GetLatencyBudgetMs() int32 {
	if x != nil {
		return x.LatencyBudgetMs
	}
	return 0
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	InputTokens   int32                  `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	FinishReason  string                 `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_proto_llm_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *GenerateResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *GenerateResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *GenerateResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *GenerateResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GenerateChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateChunk) Reset() {
	*x = GenerateChunk{}
	mi := &file_proto_llm_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateChunk) ProtoMessage() {}

func (x *GenerateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateChunk.ProtoReflect.Descriptor instead.
func (*GenerateChunk) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *GenerateChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *GenerateChunk) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type StructuredRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prompt          string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SystemPrompt    string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	JsonSchema      string                 `protobuf:"bytes,3,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	Model           string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Temperature     float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens       int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ThinkingBudget  *int32                 `protobuf:"varint,8,opt,name=thinking_budget,json=thinkingBudget,proto3,oneof" json:"thinking_budget,omitempty"`
	ServiceTier     string                 `protobuf:"bytes,9,opt,name=service_tier,json=serviceTier,proto3" json:"service_tier,omitempty"`
	RetryProfile    string                 `protobuf:"bytes,10,opt,name=retry_profile,json=retryProfile,proto3" json:"retry_profile,omitempty"`
	RequestClass    string                 `protobuf:"bytes,11,opt,name=request_class,json=requestClass,proto3" json:"request_class,omitempty"`
	LatencyBudgetMs int32                  `protobuf:"varint,12,opt,name=latency_budget_ms,json=latencyBudgetMs,proto3" json:"latency_budget_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StructuredRequest) Reset() {
	*x = StructuredRequest{}
	mi := &file_proto_llm_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredRequest) ProtoMessage() {}

func (x *StructuredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredRequest.ProtoReflect.Descriptor instead.
func (*StructuredRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{3}
}

func (x *StructuredRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StructuredRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *StructuredRequest) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *StructuredRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StructuredRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *StructuredRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *StructuredRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StructuredRequest) GetThinkingBudget() int32 {
	if x != nil && x.ThinkingBudget != nil {
		return *x.ThinkingBudget
	}
	return 0
}

func (x *StructuredRequest) GetServiceTier() string {
	if x != nil {
		return x.ServiceTier
	}
	return ""
}

func (x *StructuredRequest) GetRetryProfile() string {
	if x != nil {
		return x.RetryProfile
	}
	return ""
}

func (x *StructuredRequest) GetRequestClass() string {
	if x != nil {
		return x.RequestClass
	}
	return ""
}

func (x *StructuredRequest) GetLatencyBudgetMs() int32 {
	if x != nil {
		return x.LatencyBudgetMs
	}
	return 0
}

type StructuredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonResult    string                 `protobuf:"bytes,1,opt,name=json_result,json=jsonResult,proto3" json:"json_result,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	InputTokens   int32                  `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	SchemaValid   bool                   `protobuf:"varint,5,opt,name=schema_valid,json=schemaValid,proto3" json:"schema_valid,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredResponse) Reset() {
	*x = StructuredResponse{}
	mi := &file_proto_llm_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredResponse) ProtoMessage() {}

func (x *StructuredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredResponse.ProtoReflect.Descriptor instead.
func (*StructuredResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{4}
}

func (x *StructuredResponse) GetJsonResult() string {
	if x != nil {
		return x.JsonResult
	}
	return ""
}

func (x *StructuredResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *StructuredResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *StructuredResponse) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *StructuredResponse) GetSchemaValid() bool {
	if x != nil {
		return x.SchemaValid
	}
	return false
}

func (x *StructuredResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StructuredResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type EmbedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Text            string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Model           string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TaskType        string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LatencyBudgetMs int32                  `protobuf:"varint,5,opt,name=latency_budget_ms,json=latencyBudgetMs,proto3" json:"latency_budget_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_proto_llm_llm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{5}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *EmbedRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EmbedRequest) GetLatencyBudgetMs() int32 {
	if x != nil {
		return x.LatencyBudgetMs
	}
	return 0
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	TokenCount    int32                  `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,3,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_proto_llm_llm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbedResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *EmbedResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *EmbedResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type EmbedBatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Texts           []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Model           string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TaskType        string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LatencyBudgetMs int32                  `protobuf:"varint,5,opt,name=latency_budget_ms,json=latencyBudgetMs,proto3" json:"latency_budget_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmbedBatchRequest) Reset() {
	*x = EmbedBatchRequest{}
	mi := &file_proto_llm_llm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchRequest) ProtoMessage() {}

func (x *EmbedBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchRequest.ProtoReflect.Descriptor instead.
func (*EmbedBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{7}
}

func (x *EmbedBatchRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *EmbedBatchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedBatchRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *EmbedBatchRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EmbedBatchRequest) GetLatencyBudgetMs() int32 {
	if x != nil {
		return x.LatencyBudgetMs
	}
	return 0
}

type EmbedBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbedVector         `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchResponse) Reset() {
	*x = EmbedBatchResponse{}
	mi := &file_proto_llm_llm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchResponse) ProtoMessage() {}

func (x *EmbedBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchResponse.ProtoReflect.Descriptor instead.
func (*EmbedBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{8}
}

func (x *EmbedBatchResponse) GetEmbeddings() []*EmbedVector {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *EmbedBatchResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *EmbedBatchResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type EmbedVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	TokenCount    int32                  `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedVector) Reset() {
	*x = EmbedVector{}
	mi := &file_proto_llm_llm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedVector) ProtoMessage() {}

func (x *EmbedVector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedVector.ProtoReflect.Descriptor instead.
func (*EmbedVector) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{9}
}

func (x *EmbedVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *EmbedVector) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_llm_llm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ModelsAvailable []string               `protobuf:"bytes,3,rep,name=models_available,json=modelsAvailable,proto3" json:"models_available,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_llm_llm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_llm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_llm_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetModelsAvailable() []string {
	if x != nil {
		return x.ModelsAvailable
	}
	return nil
}

func (x *HealthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_llm_llm_proto protoreflect.FileDescriptor

const file_proto_llm_llm_proto_rawDesc = "" +
	"\n" +
	"\x13proto/llm/llm.proto\x12\x03llm\"\xa4\x04\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0estop_sequences\x18\x06 \x03(\tR\rstopSequences\x12>\n" +
	"\bmetadata\x18\a \x03(\v2\".llm.GenerateRequest.MetadataEntryR\bmetadata\x12,\n" +
	"\x0fthinking_budget\x18\b \x01(\x05H\x00R\x0ethinkingBudget\x88\x01\x01\x12!\n" +
	"\fservice_tier\x18\t \x01(\tR\vserviceTier\x12#\n" +
	"\rretry_profile\x18\n" +
	" \x01(\tR\fretryProfile\x12#\n" +
	"\rrequest_class\x18\v \x01(\tR\frequestClass\x12*\n" +
	"\x11latency_budget_ms\x18\f \x01(\x05R\x0flatencyBudgetMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_thinking_budget\"\xd1\x01\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x05R\foutputTokens\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\"^\n" +
	"\rGenerateChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\xa2\x04\n" +
	"\x11StructuredRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x1f\n" +
	"\vjson_schema\x18\x03 \x01(\tR\n" +
	"jsonSchema\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.llm.StructuredRequest.MetadataEntryR\bmetadata\x12,\n" +
	"\x0fthinking_budget\x18\b \x01(\x05H\x00R\x0ethinkingBudget\x88\x01\x01\x12!\n" +
	"\fservice_tier\x18\t \x01(\tR\vserviceTier\x12#\n" +
	"\rretry_profile\x18\n" +
	" \x01(\tR\fretryProfile\x12#\n" +
	"\rrequest_class\x18\v \x01(\tR\frequestClass\x12*\n" +
	"\x11latency_budget_ms\x18\f \x01(\x05R\x0flatencyBudgetMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_thinking_budget\"\xf4\x01\n" +
	"\x12StructuredResponse\x12\x1f\n" +
	"\vjson_result\x18\x01 \x01(\tR\n" +
	"jsonResult\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x05R\foutputTokens\x12!\n" +
	"\fschema_valid\x18\x05 \x01(\bR\vschemaValid\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x03R\tlatencyMs\"\xfb\x01\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12;\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1f.llm.EmbedRequest.MetadataEntryR\bmetadata\x12*\n" +
	"\x11latency_budget_ms\x18\x05 \x01(\x05R\x0flatencyBudgetMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\rEmbedResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x1f\n" +
	"\vtoken_count\x18\x02 \x01(\x05R\n" +
	"tokenCount\x12\x1d\n" +
	"\n" +
	"model_used\x18\x03 \x01(\tR\tmodelUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"\x87\x02\n" +
	"\x11EmbedBatchRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.llm.EmbedBatchRequest.MetadataEntryR\bmetadata\x12*\n" +
	"\x11latency_budget_ms\x18\x05 \x01(\x05R\x0flatencyBudgetMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x12EmbedBatchResponse\x120\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x10.llm.EmbedVectorR\n" +
	"embeddings\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\"F\n" +
	"\vEmbedVector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x1f\n" +
	"\vtoken_count\x18\x02 \x01(\x05R\n" +
	"tokenCount\"\x0f\n" +
	"\rHealthRequest\"{\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10models_available\x18\x03 \x03(\tR\x0fmodelsAvailable\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xea\x02\n" +
	"\n" +
	"LLMService\x127\n" +
	"\bGenerate\x12\x14.llm.GenerateRequest\x1a\x15.llm.GenerateResponse\x12<\n" +
	"\x0eGenerateStream\x12\x14.llm.GenerateRequest\x1a\x12.llm.GenerateChunk0\x01\x12C\n" +
	"\x10StructuredOutput\x12\x16.llm.StructuredRequest\x1a\x17.llm.StructuredResponse\x12.\n" +
	"\x05Embed\x12\x11.llm.EmbedRequest\x1a\x12.llm.EmbedResponse\x12=\n" +
	"\n" +
	"EmbedBatch\x12\x16.llm.EmbedBatchRequest\x1a\x17.llm.EmbedBatchResponse\x121\n" +
	"\x06Health\x12\x12.llm.HealthRequest\x1a\x13.llm.HealthResponseB>Z<github.com/wisdev/wisdev-agent-os/orchestrator/proto/llm;llmb\x06proto3"

var (
	file_proto_llm_llm_proto_rawDescOnce sync.Once
	file_proto_llm_llm_proto_rawDescData []byte
)

func file_proto_llm_llm_proto_rawDescGZIP() []byte {
	file_proto_llm_llm_proto_rawDescOnce.Do(func() {
		file_proto_llm_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_llm_llm_proto_rawDesc), len(file_proto_llm_llm_proto_rawDesc)))
	})
	return file_proto_llm_llm_proto_rawDescData
}

var file_proto_llm_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_llm_llm_proto_goTypes = []any{
	(*GenerateRequest)(nil),    // 0: llm.GenerateRequest
	(*GenerateResponse)(nil),   // 1: llm.GenerateResponse
	(*GenerateChunk)(nil),      // 2: llm.GenerateChunk
	(*StructuredRequest)(nil),  // 3: llm.StructuredRequest
	(*StructuredResponse)(nil), // 4: llm.StructuredResponse
	(*EmbedRequest)(nil),       // 5: llm.EmbedRequest
	(*EmbedResponse)(nil),      // 6: llm.EmbedResponse
	(*EmbedBatchRequest)(nil),  // 7: llm.EmbedBatchRequest
	(*EmbedBatchResponse)(nil), // 8: llm.EmbedBatchResponse
	(*EmbedVector)(nil),        // 9: llm.EmbedVector
	(*HealthRequest)(nil),      // 10: llm.HealthRequest
	(*HealthResponse)(nil),     // 11: llm.HealthResponse
	nil,                        // 12: llm.GenerateRequest.MetadataEntry
	nil,                        // 13: llm.StructuredRequest.MetadataEntry
	nil,                        // 14: llm.EmbedRequest.MetadataEntry
	nil,                        // 15: llm.EmbedBatchRequest.MetadataEntry
}
var file_proto_llm_llm_proto_depIdxs = []int32{
	12, // 0: llm.GenerateRequest.metadata:type_name -> llm.GenerateRequest.MetadataEntry
	13, // 1: llm.StructuredRequest.metadata:type_name -> llm.StructuredRequest.MetadataEntry
	14, // 2: llm.EmbedRequest.metadata:type_name -> llm.EmbedRequest.MetadataEntry
	15, // 3: llm.EmbedBatchRequest.metadata:type_name -> llm.EmbedBatchRequest.MetadataEntry
	9,  // 4: llm.EmbedBatchResponse.embeddings:type_name -> llm.EmbedVector
	0,  // 5: llm.LLMService.Generate:input_type -> llm.GenerateRequest
	0,  // 6: llm.LLMService.GenerateStream:input_type -> llm.GenerateRequest
	3,  // 7: llm.LLMService.StructuredOutput:input_type -> llm.StructuredRequest
	5,  // 8: llm.LLMService.Embed:input_type -> llm.EmbedRequest
	7,  // 9: llm.LLMService.EmbedBatch:input_type -> llm.EmbedBatchRequest
	10, // 10: llm.LLMService.Health:input_type -> llm.HealthRequest
	1,  // 11: llm.LLMService.Generate:output_type -> llm.GenerateResponse
	2,  // 12: llm.LLMService.GenerateStream:output_type -> llm.GenerateChunk
	4,  // 13: llm.LLMService.StructuredOutput:output_type -> llm.StructuredResponse
	6,  // 14: llm.LLMService.Embed:output_type -> llm.EmbedResponse
	8,  // 15: llm.LLMService.EmbedBatch:output_type -> llm.EmbedBatchResponse
	11, // 16: llm.LLMService.Health:output_type -> llm.HealthResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_llm_llm_proto_init() }
func file_proto_llm_llm_proto_init() {
	if File_proto_llm_llm_proto != nil {
		return
	}
	file_proto_llm_llm_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_llm_llm_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_llm_llm_proto_rawDesc), len(file_proto_llm_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_llm_llm_proto_goTypes,
		DependencyIndexes: file_proto_llm_llm_proto_depIdxs,
		MessageInfos:      file_proto_llm_llm_proto_msgTypes,
	}.Build()
	File_proto_llm_llm_proto = out.File
	file_proto_llm_llm_proto_goTypes = nil
	file_proto_llm_llm_proto_depIdxs = nil
}
