// Code generated by generator.go. DO NOT EDIT.

package citations

import (
	"reflect"
	"testing"
)

func TestAutoCoverageGenerated(t *testing.T) {
	_ = t
	callWithZeroValueArgs(EvaluatePromotion)
	callWithZeroValueArgs(NewResolver)
	callWithZeroValueArgs(ValidateResolveInput)
	callWithZeroValueArgs(backoffDuration)
	callWithZeroValueArgs(citationFingerprint)
	callWithZeroValueArgs(confidenceFor)
	callWithZeroValueArgs(endpointPreview)
	callWithZeroValueArgs(firstNonEmpty)
	callWithZeroValueArgs(formatID)
	callWithZeroValueArgs(isTransientDecodingError)
	callWithZeroValueArgs(normalizeArxivID)
	callWithZeroValueArgs(normalizeDOI)
	callWithZeroValueArgs(normalizeTitle)
	callMethodWithZeroReceiver[*Resolver]("Resolve")
	callMethodWithZeroReceiver[*Resolver]("WithLogger")
	callMethodWithZeroReceiver[*Resolver]("enrichFromArxiv")
	callMethodWithZeroReceiver[*Resolver]("enrichFromCrossref")
	callMethodWithZeroReceiver[*Resolver]("enrichFromOpenAlexByArxiv")
	callMethodWithZeroReceiver[*Resolver]("enrichFromOpenAlexByDOI")
	callMethodWithZeroReceiver[*Resolver]("enrichFromOpenAlexByID")
	callMethodWithZeroReceiver[*Resolver]("enrichFromOpenAlexByTitle")
	callMethodWithZeroReceiver[*Resolver]("enrichFromOpenAlexSearch")
	callMethodWithZeroReceiver[*Resolver]("enrichFromSemanticScholar")
	callMethodWithZeroReceiver[*Resolver]("getJSON")
	callMethodWithZeroReceiver[*Resolver]("getXML")
	callMethodWithZeroReceiver[*Resolver]("mergeOpenAlexItem")
}

func callWithZeroValueArgs(fn any) {
	if fn == nil {
		return
	}
	rv := reflect.ValueOf(fn)
	if rv.Kind() != reflect.Func {
		return
	}
	args := make([]reflect.Value, rv.Type().NumIn())
	for i := 0; i < rv.Type().NumIn(); i++ {
		args[i] = reflect.Zero(rv.Type().In(i))
	}

	defer func() { _ = recover() }()
	rv.Call(args)
}

func callMethodWithZeroReceiver[T any](methodName string) {
	var receiver T
	rv := reflect.ValueOf(receiver)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		rv = reflect.New(rv.Type().Elem())
	}
	m := rv.MethodByName(methodName)
	if !m.IsValid() {
		return
	}
	args := make([]reflect.Value, m.Type().NumIn())
	for i := 0; i < m.Type().NumIn(); i++ {
		args[i] = reflect.Zero(m.Type().In(i))
	}

	defer func() { _ = recover() }()
	m.Call(args)
}
