package stackconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const portsEnvFileName = "ports.env"

// maxPortsEnvWalkDepth bounds how many parent directories PortsEnvPath climbs
// looking for a wisdev-arc root or .wisdev directory. Mirrors envload.dotenv.
const maxPortsEnvWalkDepth = 8

// PortsEnvPath returns the repo-local ports file used to share auto-allocated
// stack ports across wisdev CLI invocations.
func PortsEnvPath() string {
	if explicit := strings.TrimSpace(os.Getenv("WISDEV_PORTS_ENV")); explicit != "" {
		return explicit
	}
	if cwd, err := os.Getwd(); err == nil {
		dir := cwd
		for depth := 0; depth <= maxPortsEnvWalkDepth; depth++ {
			candidate := filepath.Join(dir, ".wisdev", portsEnvFileName)
			if _, statErr := os.Stat(filepath.Join(dir, ".wisdev")); statErr == nil {
				return candidate
			}
			if isWisdevArcRoot(dir) {
				return candidate
			}
			parent := filepath.Dir(dir)
			if parent == dir {
				break
			}
			dir = parent
		}
	}
	if home, err := os.UserHomeDir(); err == nil {
		return filepath.Join(home, ".wisdev", portsEnvFileName)
	}
	return filepath.Join(".wisdev", portsEnvFileName)
}

func isWisdevArcRoot(dir string) bool {
	if _, err := os.Stat(filepath.Join(dir, "orchestrator", "cmd", "wisdev")); err == nil {
		return true
	}
	if _, err := os.Stat(filepath.Join(dir, "wisdev")); err == nil {
		return true
	}
	return false
}

// WritePortsEnv writes auto-allocated stack ports for other processes to load.
func WritePortsEnv(path string, ports StackPorts) error {
	if strings.TrimSpace(path) == "" {
		path = PortsEnvPath()
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create ports env dir: %w", err)
	}
	lines := []string{
		"# Auto-generated by wisdev stack (do not commit)",
		"WISDEV_AUTO_PORT=1",
	}
	keys := make([]string, 0, len(ports.Env()))
	for key := range ports.Env() {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		lines = append(lines, fmt.Sprintf("%s=%s", key, ports.Env()[key]))
	}
	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write ports env: %w", err)
	}
	return nil
}
