// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/wisdev/wisdev.proto

package wisdev

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_CreateSession_FullMethodName    = "/wisdev.AgentGateway/CreateSession"
	AgentGateway_GetSession_FullMethodName       = "/wisdev.AgentGateway/GetSession"
	AgentGateway_ResumeSession_FullMethodName    = "/wisdev.AgentGateway/ResumeSession"
	AgentGateway_GetNextQuestion_FullMethodName  = "/wisdev.AgentGateway/GetNextQuestion"
	AgentGateway_SubmitAnswer_FullMethodName     = "/wisdev.AgentGateway/SubmitAnswer"
	AgentGateway_ExecutePlan_FullMethodName      = "/wisdev.AgentGateway/ExecutePlan"
	AgentGateway_CancelPlan_FullMethodName       = "/wisdev.AgentGateway/CancelPlan"
	AgentGateway_ListTools_FullMethodName        = "/wisdev.AgentGateway/ListTools"
	AgentGateway_InvokeTool_FullMethodName       = "/wisdev.AgentGateway/InvokeTool"
	AgentGateway_SaveCheckpoint_FullMethodName   = "/wisdev.AgentGateway/SaveCheckpoint"
	AgentGateway_LoadCheckpoint_FullMethodName   = "/wisdev.AgentGateway/LoadCheckpoint"
	AgentGateway_ToolSearch_FullMethodName       = "/wisdev.AgentGateway/ToolSearch"
	AgentGateway_ProgrammaticLoop_FullMethodName = "/wisdev.AgentGateway/ProgrammaticLoop"
	AgentGateway_StructuredOutput_FullMethodName = "/wisdev.AgentGateway/StructuredOutput"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────────────────────────────
//
//	AgentGateway (Go) — Frontend entry point
//
// ──────────────────────────────────────────────────────────────────────
type AgentGatewayClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	ResumeSession(ctx context.Context, in *ResumeSessionRequest, opts ...grpc.CallOption) (*ResumeSessionResponse, error)
	GetNextQuestion(ctx context.Context, in *GetNextQuestionRequest, opts ...grpc.CallOption) (*GetNextQuestionResponse, error)
	SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error)
	ExecutePlan(ctx context.Context, in *ExecutePlanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlanExecutionUpdate], error)
	CancelPlan(ctx context.Context, in *CancelPlanRequest, opts ...grpc.CallOption) (*CancelPlanResponse, error)
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	InvokeTool(ctx context.Context, in *InvokeToolRequest, opts ...grpc.CallOption) (*InvokeToolResponse, error)
	SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error)
	LoadCheckpoint(ctx context.Context, in *LoadCheckpointRequest, opts ...grpc.CallOption) (*LoadCheckpointResponse, error)
	ToolSearch(ctx context.Context, in *ToolSearchRequest, opts ...grpc.CallOption) (*ToolSearchResponse, error)
	ProgrammaticLoop(ctx context.Context, in *ProgrammaticLoopRequest, opts ...grpc.CallOption) (*ProgrammaticLoopResponse, error)
	StructuredOutput(ctx context.Context, in *StructuredOutputRequest, opts ...grpc.CallOption) (*StructuredOutputResponse, error)
}

type agentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentGatewayClient{cc}
}

func (c *agentGatewayClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, AgentGateway_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, AgentGateway_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) ResumeSession(ctx context.Context, in *ResumeSessionRequest, opts ...grpc.CallOption) (*ResumeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeSessionResponse)
	err := c.cc.Invoke(ctx, AgentGateway_ResumeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) GetNextQuestion(ctx context.Context, in *GetNextQuestionRequest, opts ...grpc.CallOption) (*GetNextQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNextQuestionResponse)
	err := c.cc.Invoke(ctx, AgentGateway_GetNextQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAnswerResponse)
	err := c.cc.Invoke(ctx, AgentGateway_SubmitAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) ExecutePlan(ctx context.Context, in *ExecutePlanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlanExecutionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_ExecutePlan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutePlanRequest, PlanExecutionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ExecutePlanClient = grpc.ServerStreamingClient[PlanExecutionUpdate]

func (c *agentGatewayClient) CancelPlan(ctx context.Context, in *CancelPlanRequest, opts ...grpc.CallOption) (*CancelPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPlanResponse)
	err := c.cc.Invoke(ctx, AgentGateway_CancelPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, AgentGateway_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) InvokeTool(ctx context.Context, in *InvokeToolRequest, opts ...grpc.CallOption) (*InvokeToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeToolResponse)
	err := c.cc.Invoke(ctx, AgentGateway_InvokeTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCheckpointResponse)
	err := c.cc.Invoke(ctx, AgentGateway_SaveCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) LoadCheckpoint(ctx context.Context, in *LoadCheckpointRequest, opts ...grpc.CallOption) (*LoadCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadCheckpointResponse)
	err := c.cc.Invoke(ctx, AgentGateway_LoadCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) ToolSearch(ctx context.Context, in *ToolSearchRequest, opts ...grpc.CallOption) (*ToolSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolSearchResponse)
	err := c.cc.Invoke(ctx, AgentGateway_ToolSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) ProgrammaticLoop(ctx context.Context, in *ProgrammaticLoopRequest, opts ...grpc.CallOption) (*ProgrammaticLoopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgrammaticLoopResponse)
	err := c.cc.Invoke(ctx, AgentGateway_ProgrammaticLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayClient) StructuredOutput(ctx context.Context, in *StructuredOutputRequest, opts ...grpc.CallOption) (*StructuredOutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructuredOutputResponse)
	err := c.cc.Invoke(ctx, AgentGateway_StructuredOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
//
// ──────────────────────────────────────────────────────────────────────
//
//	AgentGateway (Go) — Frontend entry point
//
// ──────────────────────────────────────────────────────────────────────
type AgentGatewayServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	ResumeSession(context.Context, *ResumeSessionRequest) (*ResumeSessionResponse, error)
	GetNextQuestion(context.Context, *GetNextQuestionRequest) (*GetNextQuestionResponse, error)
	SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error)
	ExecutePlan(*ExecutePlanRequest, grpc.ServerStreamingServer[PlanExecutionUpdate]) error
	CancelPlan(context.Context, *CancelPlanRequest) (*CancelPlanResponse, error)
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	InvokeTool(context.Context, *InvokeToolRequest) (*InvokeToolResponse, error)
	SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error)
	LoadCheckpoint(context.Context, *LoadCheckpointRequest) (*LoadCheckpointResponse, error)
	ToolSearch(context.Context, *ToolSearchRequest) (*ToolSearchResponse, error)
	ProgrammaticLoop(context.Context, *ProgrammaticLoopRequest) (*ProgrammaticLoopResponse, error)
	StructuredOutput(context.Context, *StructuredOutputRequest) (*StructuredOutputResponse, error)
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAgentGatewayServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedAgentGatewayServer) ResumeSession(context.Context, *ResumeSessionRequest) (*ResumeSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSession not implemented")
}
func (UnimplementedAgentGatewayServer) GetNextQuestion(context.Context, *GetNextQuestionRequest) (*GetNextQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNextQuestion not implemented")
}
func (UnimplementedAgentGatewayServer) SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAnswer not implemented")
}
func (UnimplementedAgentGatewayServer) ExecutePlan(*ExecutePlanRequest, grpc.ServerStreamingServer[PlanExecutionUpdate]) error {
	return status.Error(codes.Unimplemented, "method ExecutePlan not implemented")
}
func (UnimplementedAgentGatewayServer) CancelPlan(context.Context, *CancelPlanRequest) (*CancelPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPlan not implemented")
}
func (UnimplementedAgentGatewayServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedAgentGatewayServer) InvokeTool(context.Context, *InvokeToolRequest) (*InvokeToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeTool not implemented")
}
func (UnimplementedAgentGatewayServer) SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCheckpoint not implemented")
}
func (UnimplementedAgentGatewayServer) LoadCheckpoint(context.Context, *LoadCheckpointRequest) (*LoadCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadCheckpoint not implemented")
}
func (UnimplementedAgentGatewayServer) ToolSearch(context.Context, *ToolSearchRequest) (*ToolSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToolSearch not implemented")
}
func (UnimplementedAgentGatewayServer) ProgrammaticLoop(context.Context, *ProgrammaticLoopRequest) (*ProgrammaticLoopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProgrammaticLoop not implemented")
}
func (UnimplementedAgentGatewayServer) StructuredOutput(context.Context, *StructuredOutputRequest) (*StructuredOutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StructuredOutput not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_ResumeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).ResumeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_ResumeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).ResumeSession(ctx, req.(*ResumeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_GetNextQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).GetNextQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_GetNextQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).GetNextQuestion(ctx, req.(*GetNextQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_SubmitAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).SubmitAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_SubmitAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).SubmitAnswer(ctx, req.(*SubmitAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_ExecutePlan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecutePlanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentGatewayServer).ExecutePlan(m, &grpc.GenericServerStream[ExecutePlanRequest, PlanExecutionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ExecutePlanServer = grpc.ServerStreamingServer[PlanExecutionUpdate]

func _AgentGateway_CancelPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).CancelPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_CancelPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).CancelPlan(ctx, req.(*CancelPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_InvokeTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).InvokeTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_InvokeTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).InvokeTool(ctx, req.(*InvokeToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_SaveCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).SaveCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_SaveCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).SaveCheckpoint(ctx, req.(*SaveCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_LoadCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).LoadCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_LoadCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).LoadCheckpoint(ctx, req.(*LoadCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_ToolSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).ToolSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_ToolSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).ToolSearch(ctx, req.(*ToolSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_ProgrammaticLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgrammaticLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).ProgrammaticLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_ProgrammaticLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).ProgrammaticLoop(ctx, req.(*ProgrammaticLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGateway_StructuredOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StructuredOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).StructuredOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_StructuredOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).StructuredOutput(ctx, req.(*StructuredOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdev.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _AgentGateway_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _AgentGateway_GetSession_Handler,
		},
		{
			MethodName: "ResumeSession",
			Handler:    _AgentGateway_ResumeSession_Handler,
		},
		{
			MethodName: "GetNextQuestion",
			Handler:    _AgentGateway_GetNextQuestion_Handler,
		},
		{
			MethodName: "SubmitAnswer",
			Handler:    _AgentGateway_SubmitAnswer_Handler,
		},
		{
			MethodName: "CancelPlan",
			Handler:    _AgentGateway_CancelPlan_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _AgentGateway_ListTools_Handler,
		},
		{
			MethodName: "InvokeTool",
			Handler:    _AgentGateway_InvokeTool_Handler,
		},
		{
			MethodName: "SaveCheckpoint",
			Handler:    _AgentGateway_SaveCheckpoint_Handler,
		},
		{
			MethodName: "LoadCheckpoint",
			Handler:    _AgentGateway_LoadCheckpoint_Handler,
		},
		{
			MethodName: "ToolSearch",
			Handler:    _AgentGateway_ToolSearch_Handler,
		},
		{
			MethodName: "ProgrammaticLoop",
			Handler:    _AgentGateway_ProgrammaticLoop_Handler,
		},
		{
			MethodName: "StructuredOutput",
			Handler:    _AgentGateway_StructuredOutput_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecutePlan",
			Handler:       _AgentGateway_ExecutePlan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/wisdev/wisdev.proto",
}

const (
	AcademicCapabilityService_PlanResearch_FullMethodName             = "/wisdev.AcademicCapabilityService/PlanResearch"
	AcademicCapabilityService_VerifyPlan_FullMethodName               = "/wisdev.AcademicCapabilityService/VerifyPlan"
	AcademicCapabilityService_ExecuteCapability_FullMethodName        = "/wisdev.AcademicCapabilityService/ExecuteCapability"
	AcademicCapabilityService_StreamCapability_FullMethodName         = "/wisdev.AcademicCapabilityService/StreamCapability"
	AcademicCapabilityService_GenerateStructuredOutput_FullMethodName = "/wisdev.AcademicCapabilityService/GenerateStructuredOutput"
	AcademicCapabilityService_SelectModel_FullMethodName              = "/wisdev.AcademicCapabilityService/SelectModel"
	AcademicCapabilityService_VerifyClaims_FullMethodName             = "/wisdev.AcademicCapabilityService/VerifyClaims"
	AcademicCapabilityService_RunScript_FullMethodName                = "/wisdev.AcademicCapabilityService/RunScript"
)

// AcademicCapabilityServiceClient is the client API for AcademicCapabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────────────────────────────
//
//	AcademicCapabilityService (Python) — LLM Reasoning
//
// ──────────────────────────────────────────────────────────────────────
type AcademicCapabilityServiceClient interface {
	PlanResearch(ctx context.Context, in *PlanResearchRequest, opts ...grpc.CallOption) (*PlanResearchResponse, error)
	VerifyPlan(ctx context.Context, in *VerifyPlanRequest, opts ...grpc.CallOption) (*VerifyPlanResponse, error)
	ExecuteCapability(ctx context.Context, in *ExecuteCapabilityRequest, opts ...grpc.CallOption) (*ExecuteCapabilityResponse, error)
	StreamCapability(ctx context.Context, in *ExecuteCapabilityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CapabilityChunk], error)
	GenerateStructuredOutput(ctx context.Context, in *StructuredOutputRequest, opts ...grpc.CallOption) (*StructuredOutputResponse, error)
	SelectModel(ctx context.Context, in *ModelSelectionRequest, opts ...grpc.CallOption) (*ModelSelectionResponse, error)
	VerifyClaims(ctx context.Context, in *VerifyClaimsRequest, opts ...grpc.CallOption) (*VerifyClaimsResponse, error)
	RunScript(ctx context.Context, in *RunScriptRequest, opts ...grpc.CallOption) (*RunScriptResponse, error)
}

type academicCapabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicCapabilityServiceClient(cc grpc.ClientConnInterface) AcademicCapabilityServiceClient {
	return &academicCapabilityServiceClient{cc}
}

func (c *academicCapabilityServiceClient) PlanResearch(ctx context.Context, in *PlanResearchRequest, opts ...grpc.CallOption) (*PlanResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResearchResponse)
	err := c.cc.Invoke(ctx, AcademicCapabilityService_PlanResearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicCapabilityServiceClient) VerifyPlan(ctx context.Context, in *VerifyPlanRequest, opts ...grpc.CallOption) (*VerifyPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPlanResponse)
	err := c.cc.Invoke(ctx, AcademicCapabilityService_VerifyPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicCapabilityServiceClient) ExecuteCapability(ctx context.Context, in *ExecuteCapabilityRequest, opts ...grpc.CallOption) (*ExecuteCapabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCapabilityResponse)
	err := c.cc.Invoke(ctx, AcademicCapabilityService_ExecuteCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicCapabilityServiceClient) StreamCapability(ctx context.Context, in *ExecuteCapabilityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CapabilityChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AcademicCapabilityService_ServiceDesc.Streams[0], AcademicCapabilityService_StreamCapability_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteCapabilityRequest, CapabilityChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AcademicCapabilityService_StreamCapabilityClient = grpc.ServerStreamingClient[CapabilityChunk]

func (c *academicCapabilityServiceClient) GenerateStructuredOutput(ctx context.Context, in *StructuredOutputRequest, opts ...grpc.CallOption) (*StructuredOutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StructuredOutputResponse)
	err := c.cc.Invoke(ctx, AcademicCapabilityService_GenerateStructuredOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicCapabilityServiceClient) SelectModel(ctx context.Context, in *ModelSelectionRequest, opts ...grpc.CallOption) (*ModelSelectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelSelectionResponse)
	err := c.cc.Invoke(ctx, AcademicCapabilityService_SelectModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicCapabilityServiceClient) VerifyClaims(ctx context.Context, in *VerifyClaimsRequest, opts ...grpc.CallOption) (*VerifyClaimsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyClaimsResponse)
	err := c.cc.Invoke(ctx, AcademicCapabilityService_VerifyClaims_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicCapabilityServiceClient) RunScript(ctx context.Context, in *RunScriptRequest, opts ...grpc.CallOption) (*RunScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunScriptResponse)
	err := c.cc.Invoke(ctx, AcademicCapabilityService_RunScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicCapabilityServiceServer is the server API for AcademicCapabilityService service.
// All implementations must embed UnimplementedAcademicCapabilityServiceServer
// for forward compatibility.
//
// ──────────────────────────────────────────────────────────────────────
//
//	AcademicCapabilityService (Python) — LLM Reasoning
//
// ──────────────────────────────────────────────────────────────────────
type AcademicCapabilityServiceServer interface {
	PlanResearch(context.Context, *PlanResearchRequest) (*PlanResearchResponse, error)
	VerifyPlan(context.Context, *VerifyPlanRequest) (*VerifyPlanResponse, error)
	ExecuteCapability(context.Context, *ExecuteCapabilityRequest) (*ExecuteCapabilityResponse, error)
	StreamCapability(*ExecuteCapabilityRequest, grpc.ServerStreamingServer[CapabilityChunk]) error
	GenerateStructuredOutput(context.Context, *StructuredOutputRequest) (*StructuredOutputResponse, error)
	SelectModel(context.Context, *ModelSelectionRequest) (*ModelSelectionResponse, error)
	VerifyClaims(context.Context, *VerifyClaimsRequest) (*VerifyClaimsResponse, error)
	RunScript(context.Context, *RunScriptRequest) (*RunScriptResponse, error)
	mustEmbedUnimplementedAcademicCapabilityServiceServer()
}

// UnimplementedAcademicCapabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcademicCapabilityServiceServer struct{}

func (UnimplementedAcademicCapabilityServiceServer) PlanResearch(context.Context, *PlanResearchRequest) (*PlanResearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanResearch not implemented")
}
func (UnimplementedAcademicCapabilityServiceServer) VerifyPlan(context.Context, *VerifyPlanRequest) (*VerifyPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPlan not implemented")
}
func (UnimplementedAcademicCapabilityServiceServer) ExecuteCapability(context.Context, *ExecuteCapabilityRequest) (*ExecuteCapabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCapability not implemented")
}
func (UnimplementedAcademicCapabilityServiceServer) StreamCapability(*ExecuteCapabilityRequest, grpc.ServerStreamingServer[CapabilityChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamCapability not implemented")
}
func (UnimplementedAcademicCapabilityServiceServer) GenerateStructuredOutput(context.Context, *StructuredOutputRequest) (*StructuredOutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateStructuredOutput not implemented")
}
func (UnimplementedAcademicCapabilityServiceServer) SelectModel(context.Context, *ModelSelectionRequest) (*ModelSelectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectModel not implemented")
}
func (UnimplementedAcademicCapabilityServiceServer) VerifyClaims(context.Context, *VerifyClaimsRequest) (*VerifyClaimsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyClaims not implemented")
}
func (UnimplementedAcademicCapabilityServiceServer) RunScript(context.Context, *RunScriptRequest) (*RunScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunScript not implemented")
}
func (UnimplementedAcademicCapabilityServiceServer) mustEmbedUnimplementedAcademicCapabilityServiceServer() {
}
func (UnimplementedAcademicCapabilityServiceServer) testEmbeddedByValue() {}

// UnsafeAcademicCapabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicCapabilityServiceServer will
// result in compilation errors.
type UnsafeAcademicCapabilityServiceServer interface {
	mustEmbedUnimplementedAcademicCapabilityServiceServer()
}

func RegisterAcademicCapabilityServiceServer(s grpc.ServiceRegistrar, srv AcademicCapabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedAcademicCapabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcademicCapabilityService_ServiceDesc, srv)
}

func _AcademicCapabilityService_PlanResearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanResearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCapabilityServiceServer).PlanResearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCapabilityService_PlanResearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCapabilityServiceServer).PlanResearch(ctx, req.(*PlanResearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicCapabilityService_VerifyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCapabilityServiceServer).VerifyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCapabilityService_VerifyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCapabilityServiceServer).VerifyPlan(ctx, req.(*VerifyPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicCapabilityService_ExecuteCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCapabilityServiceServer).ExecuteCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCapabilityService_ExecuteCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCapabilityServiceServer).ExecuteCapability(ctx, req.(*ExecuteCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicCapabilityService_StreamCapability_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteCapabilityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AcademicCapabilityServiceServer).StreamCapability(m, &grpc.GenericServerStream[ExecuteCapabilityRequest, CapabilityChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AcademicCapabilityService_StreamCapabilityServer = grpc.ServerStreamingServer[CapabilityChunk]

func _AcademicCapabilityService_GenerateStructuredOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StructuredOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCapabilityServiceServer).GenerateStructuredOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCapabilityService_GenerateStructuredOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCapabilityServiceServer).GenerateStructuredOutput(ctx, req.(*StructuredOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicCapabilityService_SelectModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCapabilityServiceServer).SelectModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCapabilityService_SelectModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCapabilityServiceServer).SelectModel(ctx, req.(*ModelSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicCapabilityService_VerifyClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCapabilityServiceServer).VerifyClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCapabilityService_VerifyClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCapabilityServiceServer).VerifyClaims(ctx, req.(*VerifyClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicCapabilityService_RunScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicCapabilityServiceServer).RunScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicCapabilityService_RunScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicCapabilityServiceServer).RunScript(ctx, req.(*RunScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicCapabilityService_ServiceDesc is the grpc.ServiceDesc for AcademicCapabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicCapabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdev.AcademicCapabilityService",
	HandlerType: (*AcademicCapabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlanResearch",
			Handler:    _AcademicCapabilityService_PlanResearch_Handler,
		},
		{
			MethodName: "VerifyPlan",
			Handler:    _AcademicCapabilityService_VerifyPlan_Handler,
		},
		{
			MethodName: "ExecuteCapability",
			Handler:    _AcademicCapabilityService_ExecuteCapability_Handler,
		},
		{
			MethodName: "GenerateStructuredOutput",
			Handler:    _AcademicCapabilityService_GenerateStructuredOutput_Handler,
		},
		{
			MethodName: "SelectModel",
			Handler:    _AcademicCapabilityService_SelectModel_Handler,
		},
		{
			MethodName: "VerifyClaims",
			Handler:    _AcademicCapabilityService_VerifyClaims_Handler,
		},
		{
			MethodName: "RunScript",
			Handler:    _AcademicCapabilityService_RunScript_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCapability",
			Handler:       _AcademicCapabilityService_StreamCapability_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/wisdev/wisdev.proto",
}

const (
	SearchGateway_Search_FullMethodName          = "/wisdev.SearchGateway/Search"
	SearchGateway_StreamSearch_FullMethodName    = "/wisdev.SearchGateway/StreamSearch"
	SearchGateway_IterativeSearch_FullMethodName = "/wisdev.SearchGateway/IterativeSearch"
	SearchGateway_ReRankResults_FullMethodName   = "/wisdev.SearchGateway/ReRankResults"
)

// SearchGatewayClient is the client API for SearchGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────────────────────────────
//
//	SearchGateway (Go) — Parallel Search
//
// ──────────────────────────────────────────────────────────────────────
type SearchGatewayClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	StreamSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchUpdate], error)
	IterativeSearch(ctx context.Context, in *IterativeSearchRequest, opts ...grpc.CallOption) (*IterativeSearchResponse, error)
	ReRankResults(ctx context.Context, in *ReRankRequest, opts ...grpc.CallOption) (*ReRankResponse, error)
}

type searchGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchGatewayClient(cc grpc.ClientConnInterface) SearchGatewayClient {
	return &searchGatewayClient{cc}
}

func (c *searchGatewayClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SearchGateway_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchGatewayClient) StreamSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SearchGateway_ServiceDesc.Streams[0], SearchGateway_StreamSearch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SearchGateway_StreamSearchClient = grpc.ServerStreamingClient[SearchUpdate]

func (c *searchGatewayClient) IterativeSearch(ctx context.Context, in *IterativeSearchRequest, opts ...grpc.CallOption) (*IterativeSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IterativeSearchResponse)
	err := c.cc.Invoke(ctx, SearchGateway_IterativeSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchGatewayClient) ReRankResults(ctx context.Context, in *ReRankRequest, opts ...grpc.CallOption) (*ReRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReRankResponse)
	err := c.cc.Invoke(ctx, SearchGateway_ReRankResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchGatewayServer is the server API for SearchGateway service.
// All implementations must embed UnimplementedSearchGatewayServer
// for forward compatibility.
//
// ──────────────────────────────────────────────────────────────────────
//
//	SearchGateway (Go) — Parallel Search
//
// ──────────────────────────────────────────────────────────────────────
type SearchGatewayServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	StreamSearch(*SearchRequest, grpc.ServerStreamingServer[SearchUpdate]) error
	IterativeSearch(context.Context, *IterativeSearchRequest) (*IterativeSearchResponse, error)
	ReRankResults(context.Context, *ReRankRequest) (*ReRankResponse, error)
	mustEmbedUnimplementedSearchGatewayServer()
}

// UnimplementedSearchGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchGatewayServer struct{}

func (UnimplementedSearchGatewayServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchGatewayServer) StreamSearch(*SearchRequest, grpc.ServerStreamingServer[SearchUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamSearch not implemented")
}
func (UnimplementedSearchGatewayServer) IterativeSearch(context.Context, *IterativeSearchRequest) (*IterativeSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IterativeSearch not implemented")
}
func (UnimplementedSearchGatewayServer) ReRankResults(context.Context, *ReRankRequest) (*ReRankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReRankResults not implemented")
}
func (UnimplementedSearchGatewayServer) mustEmbedUnimplementedSearchGatewayServer() {}
func (UnimplementedSearchGatewayServer) testEmbeddedByValue()                       {}

// UnsafeSearchGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchGatewayServer will
// result in compilation errors.
type UnsafeSearchGatewayServer interface {
	mustEmbedUnimplementedSearchGatewayServer()
}

func RegisterSearchGatewayServer(s grpc.ServiceRegistrar, srv SearchGatewayServer) {
	// If the following call panics, it indicates UnimplementedSearchGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchGateway_ServiceDesc, srv)
}

func _SearchGateway_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchGatewayServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchGateway_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchGatewayServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchGateway_StreamSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SearchGatewayServer).StreamSearch(m, &grpc.GenericServerStream[SearchRequest, SearchUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SearchGateway_StreamSearchServer = grpc.ServerStreamingServer[SearchUpdate]

func _SearchGateway_IterativeSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IterativeSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchGatewayServer).IterativeSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchGateway_IterativeSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchGatewayServer).IterativeSearch(ctx, req.(*IterativeSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchGateway_ReRankResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchGatewayServer).ReRankResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchGateway_ReRankResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchGatewayServer).ReRankResults(ctx, req.(*ReRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchGateway_ServiceDesc is the grpc.ServiceDesc for SearchGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdev.SearchGateway",
	HandlerType: (*SearchGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchGateway_Search_Handler,
		},
		{
			MethodName: "IterativeSearch",
			Handler:    _SearchGateway_IterativeSearch_Handler,
		},
		{
			MethodName: "ReRankResults",
			Handler:    _SearchGateway_ReRankResults_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSearch",
			Handler:       _SearchGateway_StreamSearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/wisdev/wisdev.proto",
}
