// Code generated by generator.go. DO NOT EDIT.

package paper

import (
	"reflect"
	"testing"
)

func TestAutoCoverageGenerated(t *testing.T) {
	_ = t
	callWithZeroValueArgs(ExtractPDFText)
	callWithZeroValueArgs(GenerateHTML)
	callWithZeroValueArgs(GenerateLaTeX)
	callWithZeroValueArgs(GenerateMarkdown)
	callWithZeroValueArgs(NewProfiler)
	callMethodWithZeroReceiver[*Profiler]("ExtractProfile")
}

func callWithZeroValueArgs(fn any) {
	if fn == nil {
		return
	}
	rv := reflect.ValueOf(fn)
	if rv.Kind() != reflect.Func {
		return
	}
	args := make([]reflect.Value, rv.Type().NumIn())
	for i := 0; i < rv.Type().NumIn(); i++ {
		args[i] = reflect.Zero(rv.Type().In(i))
	}

	defer func() { _ = recover() }()
	rv.Call(args)
}

func callMethodWithZeroReceiver[T any](methodName string) {
	var receiver T
	rv := reflect.ValueOf(receiver)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		rv = reflect.New(rv.Type().Elem())
	}
	m := rv.MethodByName(methodName)
	if !m.IsValid() {
		return
	}
	args := make([]reflect.Value, m.Type().NumIn())
	for i := 0; i < m.Type().NumIn(); i++ {
		args[i] = reflect.Zero(m.Type().In(i))
	}

	defer func() { _ = recover() }()
	m.Call(args)
}
